### ISSUE TITLE
24 hours still don't approve my transaction. Ticket ID #199416

### ISSUE THREAD

**Issue by jacksparrow1608** [hitbtc-com/hitbtc-api#104]
I'm really feeling angry now. I withdrew my STRAT 24 hours ago and until now you still don't approve my transaction. Even the worst bank in the world can do better than you.

**Comment by aaahmadi** [comment]
meybe hitbtc prodect ur wrong treade

**Comment by hitbtc-com** [comment]
Dear @jacksparrow1608, can you please let us know if you still experience any issues and provide us with a support ticket number if you do? Thanks in advance!
