### ISSUE TITLE
where is my deposit BCH admin HITBTC is pased 2 days and to my account is 0 bch 

### ISSUE THREAD

**Issue by leontesabian** [hitbtc-com/hitbtc-api#105]
where is my deposit BCH admin is pased 2 days and to my account is 0 bch 
what kind of exchange you are and where is my 0.4999 BCH 
Time: 2018-01-17 00:48:58 
Address: 15YXQAC8kHM8ge2PiypuBwg9QPvQhGZLat 
TxID: feb6b2793a0efe9ebae4a90eb75cb35f36e6088f3ca01a754f50c44493dfaa91

**Comment by leontesabian** [comment]
scam exchanger 
where is my deposit BCH admin is pased 2 days and to my account is 0 bch 
what kind of exchange you are and where is my 0.4999 BCH
Time: 2018-01-17 00:48:58 
 Address: 15YXQAC8kHM8ge2PiypuBwg9QPvQhGZLat
 TxID: feb6b2793a0efe9ebae4a90eb75cb35f36e6088f3ca01a754f50c44493dfaa91


TweetTweet, pagina attuale. Tweet e risposte Contenuti

HitBTC
‏
 
@hitbtc
 13 h13 ore fa
Altro
Dear traders, a certain amount of BCH deposits might have been delayed during a past couple of days. This happened as we have been relocating to new BCH address format. All missing deposits will catch up during next 12 hours.

Traduci dalla lingua originale: inglese

**Comment by SACHINMALIK28793** [comment]
where is my deposit ECH admin is pased 26 days and to my account is 0 bch
Time: 1/8/2018, 11:56:47 AM
Address: 0x2cbec495e90a6ac7a8c3a052586fadd4deef7f6f
From TxID: 0x2cbec495e90a6ac7a8c3a052586fadd4deef7f6f
to TxID: 0x3e76e6171bd2209134b4a34ff40c7b9bd0252328
Tx Hash : 0x7c404904175b607e58c93a45a2adcc00f26584de014f943a03191c594923be32
ECH : 172.00
USD : 258.00
![caddy wallet coin transaction](https://user-images.githubusercontent.com/36023467/35744526-9ac6cac6-0866-11e8-8ac5-2bae69f94057.png)
![hitbtc 1](https://user-images.githubusercontent.com/36023467/35744527-9af28378-0866-11e8-94da-7deb9b92f194.jpg)

**Comment by hitbtc-com** [comment]
Dear @leontesabian and @SACHINMALIK28793, would you be so kind as to provide us with your support ticket numbers if the issue still persists? Thanks in advance!
