### ISSUE TITLE
Api V2 REST: stoplimit order problem

### ISSUE THREAD

**Issue by wificoins** [hitbtc-com/hitbtc-api#107]
There seems to be a small bug in /api/2/order.

API v2 allows to create a new order type stopLimit with stopPrice. When I post such an order the order is created, but the API does not return any information other than 504 gateway error (after 30 seconds or so). This is always the same, no exceptions.
Orders without stopPrices are handled as expected.

My conclusion is that there is a small bug.
postData:         [symbol=XEMBTC, clientOrderId=1516444212572000, side=sell, type=stopLimit, quantity=6.0, price=0.00009047, stopPrice=0.000090189]
response:         {"error":{"code":504,"message":"Gateway Timeout","description":""}}

Possibly I made a mistake. If so please advice.
Best regards,
Gerrit

**Comment by hitbtc-com** [comment]
hi @wificoins 
We'll check it out

thx

**Comment by hitbtc-com** [comment]
fixed
