### ISSUE TITLE
Please solve the Ticket # 16101/188683/192649

### ISSUE THREAD

**Issue by anupsingh1210** [hitbtc-com/hitbtc-api#108]
@hitbtc-com  I had send bitcoin from my Bitoasis wallet to my Hitbtc a/c, but by mistake i sent bitcoin on USDT address instead of BTC address. Already submitted all the details  **@( Ref Ticket # Ref Ticket # 16101/188683/192649)**  but still not received any reply from HITBTC.

![btc wrong transfer 4](https://user-images.githubusercontent.com/35521020/35184821-ec5673ee-fe13-11e7-9e86-84a55b94b596.jpg)
![btc wrong transfer 5](https://user-images.githubusercontent.com/35521020/35184822-ec88bb9c-fe13-11e7-9f50-c60df9666bd9.jpg)
![btc wrong transfer](https://user-images.githubusercontent.com/35521020/35184823-ecb42048-fe13-11e7-8cc7-2cbde2d1b8cc.jpg)

https://blockchain.info/tx/ec08e62a4e6daff112046b8d9ea28e01e73819f90c21eb5df1979fc470829cf2
 

Regards,
Anup

**Comment by hitbtc-com** [comment]
Send it support pliz.
