### ISSUE TITLE
Where's my deposit

### ISSUE THREAD

**Issue by olabiyio** [hitbtc-com/hitbtc-api#109]
@hitbtc-com 
I sent Crypto pay to your deposit address at 12.20 pm today and it's still not on the exchange. Can you please resolve this please? your support center on the website does not work either and no ones replying tweets.. this is a shamble. 

my txt hash for my deposit is below:
https://etherscan.io/tx/0x6c03d67311079cb62f86d2880f4e6d0d731ce235907ac369e48d03e4b279509b

can someone please get back to me asap on my email oolabiyio@gmail.com. thank you

**Comment by hitbtc-com** [comment]
Send to support pliz.
