### ISSUE TITLE
HitBTC get hacked?

### ISSUE THREAD

**Issue by jacksparrow1608** [hitbtc-com/hitbtc-api#110]
I deposited ADEX to my ADEX wallet on HitBTC yesterday. I still not received it yet. But when I checked on etherscan.io, they was sent to another address from my ADEX wallet on HitBTC. That means my HitBTC account has received ADEX and then sent to another address. What I do not understand is that when I check the transfer history, there is no information about any ADEX transfers. My support ticket: #208231
Hope your response soon. Many thanks

**Comment by cabuloglucihan** [comment]
Please fix my ticket #191633

**Comment by hitbtc-com** [comment]
>> That means my HitBTC account has received ADEX and then sent to another address.

This is a part of regular exchange operations. Funds are not being stored on those wallets which they were deposited to.

>> What I do not understand is that when I check the transfer history, there is no information about any ADEX transfers. 

We have processed your transaction and it has reached your HitBTC account. Sorry about the delay.
