### ISSUE TITLE
HitBTC stolen my ADX. I'm going to send this report to newspapers if HitBTC doesn't pay me back.

### ISSUE THREAD

**Issue by jacksparrow1608** [hitbtc-com/hitbtc-api#112]
On Jan 20th, i deposited ADX to my ADX wallet on HitBTC but it pass 3 days and i still don't recieve my ADX. When i checked it on tranfer history, there is nothing but when i checked it on etherscan, my ADX was successfully transferred but it was sent to another wallet shortly afterwards and HitBTC has not recorded anything about that transaction. If my account was hacked, the transfer history would record that transfer but because HitBTC itself has stolen my ADX, so in the transfer history there is no ADX transaction. I also sent a support ticket 3 days ago but they don't reply. They even deleted it. Support ticket: #208231.
This is my ADX wallet on HitBTC: 0xA0e65B533cfbc6260e02cf591093268935233432

**Comment by hitbtc-com** [comment]
Send it to support pliz.

**Comment by jacksparrow1608** [comment]
i did it but your support central don't respond me. i already posted on github, reddit,hitbtc forum, hitbtc bug report but no one give me a response
