### ISSUE TITLE
WS API works incorrect, wrong orderbook data recieved

### ISSUE THREAD

**Issue by serzhiio** [hitbtc-com/hitbtc-api#113]
Maybe any of tech stuff will hear me.
WS API is working bad, some of my instances recieve incorrect orderbook with wrong dates, prices.
Please have it fixed!

**Comment by artempankov** [comment]
And sometimes orderbook and ticker data stops sending to websocket at all

**Comment by mvp83** [comment]
have same problem (there no update of orderbook event)

**Comment by benderoki** [comment]
https://forum.hitbtc.com/discussion/9040/api-issues
https://forum.hitbtc.com/discussion/9105/critical-bug-hitbtc-api-is-totally-broken-and-returns-random-data
This bug is more than 24 hours old. All API methods send incorrect data

**Comment by Ro0TT** [comment]
Support / Dev do not expect an answer?

**Comment by jethmalani** [comment]
I am having the same problem. Update messages aren't coming through! Glad to know I am not the only one. My issue is exactly like @brianwozeniak

**Comment by Andersoonalves** [comment]
I am having the same problem. Update messages aren't coming through! Glad to know I am not the only one.

**Comment by Andersoonalves** [comment]
I am having same problem (there no update of orderbook event). Support has any answer?

**Comment by KelvinJones** [comment]
Same problem here. Just adding my "vote" to this.

@HitBTC dev team - servers require regular restarts regardless of their OS.  If the api code/software is solid, schedule weekly restarts on your API server(s) for us please. ;-)  If that doesn't work, increase the frequency.  If you DAG them you can do this transparently too, even restart during the day!

There, I feel better now that I've added my 2cents on part of the solution. ;-) I'm just one of those people.

**Comment by Pat71** [comment]
same here, the API is useless at the moment :-(

**Comment by keeroo1337** [comment]
This API is really great with very low latency response times. So sad it is currently broken.

**Comment by jethmalani** [comment]
Is anybody else getting incorrect order book data when using the API not the WS?

**Comment by KelvinJones** [comment]
Yes. HitBTC still not working as far as I know.

--
c: +27 83 682 2660
e: kelvin@cloud29.co.za
in: https://za.linkedin.com/in/kelvin-jones-01a3a56

Sent from my cell phone

________________________________

**Comment by xpl** [comment]
same problem, API gone crazy (tried REST and WS ver.1), lost a lots of money due to incorrect orders in the orderbook

**Comment by brianwozeniak** [comment]
Things seem better today with the streaming API, its been up for around 10 hours straight now. Hopefully they found a solution. Still wish they would communicate the status so we know. Just a quick update when things aren't working correctly would be re-assuring.

**Comment by KelvinJones** [comment]
Agreed!  It does seem better at the moment but when I run the bot in debug mode I still get the errors, cant’ read the wallet and quotes. I wonder if that’s due to being locked and not running in “Free” mode?


--
c: +27 83 682 2660
e: kelvinjones@outlook.com
in: https://za.linkedin.com/in/kelvin-jones-01a3a56

**Comment by brianwozeniak** [comment]
I am starting to see signs the streaming API is having issues again. Just started about 15-20 minutes ago, and at times the stream is not sending anything just like before. As I am watching it I can see it will work for a bit, and then stop. Appears to be struggling on their end.

**Comment by jethmalani** [comment]
Even I am seeing a bunch of issues with the WS and REST API returning errors.

**Comment by hitbtc-com** [comment]
FIXED

**Comment by dhelland** [comment]
I'm experiencing the issues described above with subscribeOrderbook.

**Comment by serzhiio** [comment]
@hitbtc-com, yes issues are here

**Comment by brianwozeniak** [comment]
Looks like the issues are back today. The web socket stream is no longer sending data. Been happening for about 1 hour now.

**Comment by infinityCounter** [comment]
Having similar issues with subscribeOrderbook and subscribeTrades. No data being received after initial success result response for subscribeOrderbook
