### ISSUE TITLE
Deposit issue

### ISSUE THREAD

**Issue by siddharthgoel1990** [hitbtc-com/hitbtc-api#115]
Hi, I have deposited ppt coin on 21st jan 2018 to hitbtc and till today its not yet credited to my account.
I have checked the transaction, it was successful with more than 10000+ confirmation.
Not able to understand why is it taking so long to credit my account. Kindly check Ticket ID #214630.

**Comment by hitbtc-com** [comment]
Send it to support pliz.

**Comment by siddharthgoel1990** [comment]
Send the issue to support many times and also have raised the ticket but till today no reply.I request you to please connect them to me. 
Or please let me know if there is any email id which i can connect to.
Regards,Siddharth Goel

    On Monday 29 January 2018, 10:29:58 PM IST, hitbtc-com <notifications@github.com> wrote:  
 
 
Send it to support pliz.

**Comment by siddharthgoel1990** [comment]
Hi, i have not yet received my deposit of ppt coin. Been already 8 days. Kindly check and provide me with the solution.Request you to please check and provide me with the solution.
No one is replying from the support. Kindly help.
Regards,Siddharth Goel

    On Monday 29 January 2018, 10:29:58 PM IST, hitbtc-com <notifications@github.com> wrote:  
 
 
Closed #115.

**Comment by hitbtc-com** [comment]
Sent your request to our support directly.

**Comment by siddharthgoel1990** [comment]
Please share the email id of the support. I have raised the ticket 8=10 times but no reply till today.Do let me know the support email id so that i can email.
Please understand my issue and help me out.
Regards,
Siddharth Goel
    On Monday 29 January 2018, 11:08:49 PM IST, hitbtc-com <notifications@github.com> wrote:  
 
 
Sent your request to our support directly.

**Comment by siddharthgoel1990** [comment]
I am getting only this reply everytime i raise the ticket - 

Dear Trader,

Thank you for contacting HitBTC Support!

Your ticket has been registered with the Ticket ID #221058.

Please note that the majority of requests require research to resolve, and it can sometimes take us up to 48 hours to respond, though we make every effort to get back to you as quickly as possible and most queries are answered within 24 hours.

To provide us with additional details or updates, please reply to this e-mail or use the HitBTC Support web form under the following link: https://hitbtc.com/support

Once again, thank you for getting in touch.

Regards,
HitBTC Support team


    On Monday 29 January 2018, 11:16:39 PM IST, Siddharth Goel <siddharthgoel1990@yahoo.com> wrote:  
 
  Please share the email id of the support. I have raised the ticket 8=10 times but no reply till today.Do let me know the support email id so that i can email.
Please understand my issue and help me out.
Regards,
Siddharth Goel
    On Monday 29 January 2018, 11:08:49 PM IST, hitbtc-com <notifications@github.com> wrote:  
 
 
Sent your request to our support directly.

**Comment by siddharthgoel1990** [comment]
Hi,
I am still waiting for my deposit. request you to please check
Regards,Siddharth Goel

    On Monday 29 January 2018, 11:17:18 PM IST, Siddharth Goel <siddharthgoel1990@yahoo.com> wrote:  
 
  I am getting only this reply everytime i raise the ticket - 

Dear Trader,

Thank you for contacting HitBTC Support!

Your ticket has been registered with the Ticket ID #221058.

Please note that the majority of requests require research to resolve, and it can sometimes take us up to 48 hours to respond, though we make every effort to get back to you as quickly as possible and most queries are answered within 24 hours.

To provide us with additional details or updates, please reply to this e-mail or use the HitBTC Support web form under the following link: https://hitbtc.com/support

Once again, thank you for getting in touch.

Regards,
HitBTC Support team


    On Monday 29 January 2018, 11:16:39 PM IST, Siddharth Goel <siddharthgoel1990@yahoo.com> wrote:  
 
  Please share the email id of the support. I have raised the ticket 8=10 times but no reply till today.Do let me know the support email id so that i can email.
Please understand my issue and help me out.
Regards,
Siddharth Goel
    On Monday 29 January 2018, 11:08:49 PM IST, hitbtc-com <notifications@github.com> wrote:  
 
 
Sent your request to our support directly.

**Comment by cabuloglucihan** [comment]
Hitbtc is a scam and thief exchange company. They didnt fix my ticket#191633 for 22 days
