### ISSUE TITLE
Insufficient funds error when funds are sufficient 

### ISSUE THREAD

**Issue by jethmalani** [hitbtc-com/hitbtc-api#117]
I am getting an Insufficient funds error when placing market order even though I have enough money in my trading account for the cost and including fees. These are funds that are in my trading account as well. This is happening when using the API and the web dashboard. It doesn't always happen but I will have like 300-400 in excess of what is need to make a trade and it will tell me Insufficient funds. Is anybody else experiencing this issue?

**Comment by hitbtc-com** [comment]
use limit order.
if you are using market order, add around 10% for reserved

**Comment by bohdanz1997** [comment]
I've got answer:

> Nelly Marsh (HitBTC)
> 
> Sep 27, 07:28 WEST
> 
> Dear trader,
> 
> Thank you for reaching out!
> 
> When purchasing a large quantity of cheap currency, the displayed fee can exceed 0.1%.
> 
> The fee from each possible trade is being rounded to the nearest computable value. The sum of this values is shown in the interface. But this does not mean that this size will really be written off from user's account. 
> 
> This happens as for the worst possible scenario, this order will get executed in a bunch of trades, each of which will have a minimum size. And the total fee from all these trades will have a frightening size.
> 
> However, this scenario is barely achievable, so fees are always less than the amount specified.
> добрый день вот ответ
