### ISSUE TITLE
Affiliate Count and Earnings 

### ISSUE THREAD

**Issue by macd2** [hitbtc-com/hitbtc-api#118]
![count](https://user-images.githubusercontent.com/30157354/35477040-4981195a-03bb-11e8-80d7-cebf08e6d75d.png)

I get a bit angry here. The Affiliate count is not working again for a Month??
Also there are many "Earnings: 0 counts" 
Is it so hard to fix this issue?

**Comment by cabuloglucihan** [comment]
Please dolve ticket number #191633

**Comment by macd2** [comment]
which ticket number you want of the approximately 10 open tickets nobody answers?
 But the latest one is this: #181743

**Comment by cabuloglucihan** [comment]
Yeah i have about 10 tickets to fix. But hitbtc dont show response. İ need to sign in account but i cant log in because of 2fa lost

**Comment by macd2** [comment]
hitBTC is a mess as far as the Support is concerned.
@hitbtc-com what is now about this issue?

**Comment by cabuloglucihan** [comment]
@hitbtc-com is a scam i think they stole my coins. And also they dont reply me on support

**Comment by macd2** [comment]
@hitbtc-com whats going on?
the issue is still the same!!!!!!

**Comment by Luckygerman** [comment]
@hitbtc-com answer

**Comment by Luckygerman** [comment]
It isnt solved??

Verstuurd vanaf mijn iPhone

**Comment by macd2** [comment]
no it is not!

**Comment by Luckygerman** [comment]
Than solve it!

Verstuurd vanaf mijn iPhone
