### ISSUE TITLE
Incorrect trades filtration

### ISSUE THREAD

**Issue by kononencheg** [hitbtc-com/hitbtc-api#119]
filtered trades for the last hour, but got 2013 year:

curl -X GET -u "pub:secret" "https://api.hitbtc.com/api/2/public/trades/BTCUSD?from=2018-01-30T22:33Z&till=2018-01-30T23:33Z"

```
[{"id":2018,"price":"731.95","quantity":"0.62","side":"buy","timestamp":"2013-12-27T22:09:39.339Z"}]
```

**Comment by hitbtc-com** [comment]
fixed
