### ISSUE TITLE
2-Factor Authetication not working.

### ISSUE THREAD

**Issue by bjtheman** [hitbtc-com/hitbtc-api#121]
I have an account with HitBTC and have tried to change my 2FA authentication recently.
Although I verified and confirmed by replying to an email, the code obtained from google authenticator does not work and do not let me access my account.
I have already placed 5 online request ,with all relevant ID's and transaction information,  to take google authentication out from my account.
Please have a look and advise ASAP.

**Comment by hitbtc-com** [comment]
Please make sure that your date, time and timezone settings are the same and precisely correct on your phone and your computer. That is a common reason for such trouble.

**Comment by bjtheman** [comment]
Yes I have checked it few times and made sure..but still not resolves..regardless...it should still let me log in with the backup code..which is not the case either. So, please take 2FA authentication from my account.
I have paced my request to support team 5 times in last 20days. See attached JPG if you can see it.
![hitbtc google code](https://user-images.githubusercontent.com/36034404/35756406-4cd01760-08bf-11e8-9c0e-fd972149fdec.JPG)

**Comment by saminsta** [comment]
Nice service provided by this blog. One more platform are available for resolving all [**HitBTC Support Number**](https://www.walletonline.info/exchange/hitbtc-support-number/) issues . My experience is good with this help-desk on this help-desk available toll-free number 1-800-509-3075 for all USA, UK & Australia customers.
