### ISSUE TITLE
2FA is not Working. Please disable from my account.

### ISSUE THREAD

**Issue by bjtheman** [hitbtc-com/hitbtc-api#122]
I have an account with HitBTC and have tried to change my 2FA authentication recently.
Although I verified and confirmed by replying to an email, the code obtained from google authenticator does not work and do not let me access my account.
I have already placed 5 online request ,with all relevant ID's and transaction information, to take google authentication out from my account.
Please have a look and advise ASAP.

I have check time on my phone, but thing is ...it does not even accept backup code..so please dont ask again to check it. Also, please dont ask me to put it thru the support which i have done 5 times before I came on this site. So, please get the things done instead telling same thing again and again.

**Comment by hitbtc-com** [comment]
Dear @bjtheman, have you contacted the support? Is the issue still relevant? Please, let us know. Thanks!
