### ISSUE TITLE
Affiliate program is scam

### ISSUE THREAD

**Issue by vendetta19** [hitbtc-com/hitbtc-api#123]
I have attracted 145 users through HITBTC's affiliate program. Including my family. I realized That their affiliate programs do not work at all. HITBTC answered my question a few days ago.

"Hi! Please accept our apologies for any delays with the response and inconvenience caused. Our engineers are currently researching the problem. We are sure the resolving won't take long."

But the damn reply is exactly the same as last September's. The affiliate program hasn't worked at all in half a year, and HITBTC has absolutely no intention of solving this problem. They don't tell us anything about what's wrong with it and when it will be solved.

**Comment by DangBaby** [comment]
me too

**Comment by Luckygerman** [comment]
Hello Hitbtc,

Your affiliate is not working for more than a year right now??? Do something!

**Comment by Luckygerman** [comment]
Isnt solved yet!

Verstuurd vanaf mijn iPhone
