### ISSUE TITLE
canceled response to cancelReplace request

### ISSUE THREAD

**Issue by alexanderborsch** [hitbtc-com/hitbtc-api#125]
Request: {'params': {'clientOrderId': 'ryaKWfF3EVfBALaWQvnAwaYt9rn5Zlkj', 'requestClientId': 'Nuf3tycefJrVCZuXOOSHxG8O60SoO1AH', 'price': 5.077559999999999, 'quantity': 2.73}, 'method': 'cancelReplaceOrder', 'id': 15181913629473}
Response: {u'jsonrpc': u'2.0', u'result': {u'status': u'canceled', u'clientOrderId': u'ryaKWfF3EVfBALaWQvnAwaYt9rn5Zlkj', u'cumQuantity': u'0.00', u'symbol': u'BNTUSD', u'side': u'buy', u'timeInForce': u'GTC', u'reportType': u'canceled', u'updatedAt': u'2018-02-09T15:49:22.956Z', u'price': u'5.07754', u'type': u'limit', u'id': u'16486022697', u'createdAt': u'2018-02-09T15:49:15.100Z', u'quantity': u'0.76'}, u'id': 15181913629473}

**Comment by hitbtc-com** [comment]
If, for example, you don't have enough money for order with new quantity and price, then origin order canceled.
"cancelReplace" - request first cancel origin order and replace it (if it can be available) new order cumQuantity inherited origin order. Also cancel and place new order - atomic operation
