### ISSUE TITLE
Incorrect order date in dashboard

### ISSUE THREAD

**Issue by divergence082** [hitbtc-com/hitbtc-api#128]
"createdAt":"2018-02-12T21:09:34.665Z","updatedAt":"2018-02-12T21:09:34.665Z" 
for `new` order in api response
and Date(UTC) = `2018-12-02 21:09:34.665` in dashboard.
Date format should be yyyy-MM-dd not yyyy-dd-MM

**Comment by hitbtc-com** [comment]
what do you mean by "dashboard"?

**Comment by divergence082** [comment]
https://hitbtc.com/reports/orders - there

**Comment by hitbtc-com** [comment]
Thank you
