### ISSUE TITLE
include "id" in websocket updates and snapshots

### ISSUE THREAD

**Issue by jrobinson01** [hitbtc-com/hitbtc-api#129]
Is it possible to include the id passed to subscription methods in snapshot and update messages? When calling `subscribeCandles` an id is passed. It would be really useful to have that id included in the subsequent `snapshotCandles` events.

**Comment by hitbtc-com** [comment]
http://www.jsonrpc.org/specification#notification
A Notification is a Request object without an "id" member. A Request object that is a Notification signifies the Client's lack of interest in the corresponding Response object, and as such no Response object needs to be returned
