### ISSUE TITLE
ChronoBank time deposit not reflecting in the my HitBTC(Account)

### ISSUE THREAD

**Issue by lambertino1** [hitbtc-com/hitbtc-api#132]
Dear Support,

I transfer 4.88847113 TIME TOKEN (Chrono Bank) to my account on Jan-09-2018. the transaction was successful but the token did NOT reflect in my account on the exchange platform(HitBTC.com).

See below transaction hash ID and attachment for further detail.

Kindly rectify as soon as possible

https://etherscan.io/tx/0xcdd544e2e9c3a6e3937e44e9bd58ff877bcfc6050c1a1d2ae3a88647a47dc288

My account details

Profile: adeoyelambert@gmail.com

Username: adeoyelambert

MY etherwallet address: 0x2c5354df6699cc27fc9e0bbb93088e029fb6d60a

Address: ether sent to: 0x9dde3155eb392b58c14d4c7cc290397137105e70

https://etherscan.io/token/TIME?a=0x9dde3155eb392b58c14d4c7cc290397137105e70

**Comment by turkig5** [comment]
It is secured by a seat where they have no impediments and no protection for traders

**Comment by hitbtc-com** [comment]
Dear @lambertino1, have you contacted our support regarding this issue? Do you have a ticket number? Please, provide it if the issue's still relevant. Thanks!

**Comment by lambertino1** [comment]
Dear

See list of ticket raised since January 9, 2018 (189days) without no
resolution.

Ticket ID #215688
Ticket ID #328275
Ticket ID #250794
Ticket ID #250788
Ticket ID #170720
Ticket ID #204300
Ticket ID #215688
Ticket ID #212202
Ticket ID #204300
Ticket ID #250794

See below transaction hash ID

Hash ID:  0xcdd544e2e9c3a6e3937e44e9bd58ff877bcfc6050c1a1d2ae3a88647a47dc288


https://etherscan.io/tx/0xcdd544e2e9c3a6e3937e44e9bd58
ff877bcfc6050c1a1d2ae3a88647a47dc288

My account details

Profile: adeoyelambert@gmail.com

Username: adeoyelambert

MY etherwallet address: 0x2c5354df6699cc27fc9e0bbb93088e029fb6d60a

Address: ether sent to: 0x9dde3155eb392b58c14d4c7cc290397137105e70
