### ISSUE TITLE
help

### ISSUE THREAD

**Issue by isaeyibil** [hitbtc-com/hitbtc-api#134]
I have an account with HitBTC and recently I tried to change 2FA authentication.
If I verify and verify by replying to an email, the code from Google Authenticator does not work and does not allow me to access the account.
I found 5 online requests with all relevant identity and transaction information to remove Google authentication from my account.
Please take a look and let us know as soon as possible.

**Comment by aaahmadi** [comment]
Hello Isaeyibil im fixed this problem and hitbtc removed my 2fa and backed me my accounte 
pls don't worry and send emails too hitbtc support and don't rush 
hitbtc back ur accounte and u can treade again 
its ok 👍

**Comment by Graal46** [comment]
Пиши по Русски !

**Comment by hitbtc-com** [comment]
Send your request to remove a 2FA into support plz.

**Comment by isaeyibil** [comment]
I want to lift 2 fa. thanks a lot for your help
