### ISSUE TITLE
Missing coins Ticket closed without any solution

### ISSUE THREAD

**Issue by jojoba72** [hitbtc-com/hitbtc-api#135]
Gents - please check Ticket #245035 ... I had to raise a second Ticket since you just closed the first one without solution. Still Missing 1650 NGCs!!!

**Comment by Gkathuria2** [comment]
My XEM withdrawal is pending from last 60 hours

Operational id is a58bd9db-2f8f-44f7-b585-dd94913b6712

kindly check these tickets #251471
#251092

Now XEM is offline on receiving address, please cancel withdrawal request and add fund back.

@HitBTC_Support_Team

**Comment by jojoba72** [comment]
What is this about?

Sent from my iPhone

On 9 Mar 2018, at 10:12, Gkathuria2 <notifications@github.com> wrote:

My XEM withdrawal is pending from last 60 hours

Operational id is a58bd9db-2f8f-44f7-b585-dd94913b6712

kindly check these tickets #251471
#251092

Now XEM is offline on receiving address, please cancel withdrawal request and add fund back.

@HitBTC_Support_Team

**Comment by hitbtc-com** [comment]
Dear @jojoba72, I believe your issue was successfully resolved. Enjoy trading with HitBTC!
