### ISSUE TITLE
A problem with balances (showing different values with each request)

### ISSUE THREAD

**Issue by xpl** [hitbtc-com/hitbtc-api#137]
I use REST api v2 for querying balances. They gone totally crazy today, showing incorrect (obsolete?) values each other request. For example (a series of subsequent calls to balances update):

```
fetching balances...
{ BTC: 0.007073215, BTG: 0.00054258, ETH: 0.756 }
```
```
fetching balances...
{ BTC: 0.017781009, BTG: 0.00054258, ETH: 0.626 }
```
```
fetching balances...
{ BTC: 0.007073215, BTG: 0.00054258, ETH: 0.756 }
```

As you can see, the balances flip their value each time I request them. I'm 100% sure it's not an error on my side, because the website shows incorrect balances as well: with each page refresh, I get "new" values.

Looks like a problem with caching on your side or whatever. Please fix it.

<i>P.S. I develop the [CCXT library](https://github.com/ccxt/ccxt). It is a cross-language cryptocurrency trading library with support for more than 90 exchanges.</i>

**Comment by jethmalani** [comment]
I am seeing the same issue on with the API and on the web app

**Comment by hitbtc-com** [comment]
Issues have been with one of our backend. 
Thank you for your attentions.
