### ISSUE TITLE
My XEM withdrawal is pending.

### ISSUE THREAD

**Issue by Gkathuria2** [hitbtc-com/hitbtc-api#141]
My XEM withdrawal is pending from last 30 hours details as follows 

Operational id is   a58bd9db-2f8f-44f7-b585-dd94913b6712

Transaction Hash   eaca961f41bc462fd3ea7167f87d98ca09172f8d65ff8bf0c8a77227dcf4152b

To Address    ND2JRPQIWXHKAA26INVGA7SREEUMX5QAI6VU7HNR

Payment Id is    8e7927a8a44c412086b

Above mentioned Transaction Hash have no info on NEM explorer. 

Withdrawal after mine is continued processed as I can see in system health section.

Pending oldest withdrawal on 2018-03-07 06:22 is mine I think because of withdrawal confirmation email I received just 1 minute before i.e. on 2018-03-07 06:21

![capture xem](https://user-images.githubusercontent.com/37172632/37139389-b6149c9a-22d3-11e8-9582-b8cfc7bbd4ae.JPG)

Kindly solve this issue ASAP

**Comment by Gkathuria2** [comment]
kindly check these tickets #251471
#251092
#251688
#251768
 My XEM withdrawal is not processed by @hitbtc
Showing oldest on system health section is mine.
0

**Comment by hitbtc-com** [comment]
Dear @Gkathuria2,
This transaction was canceled and the funds have returned to your account.
We appreciate your choice to trade with HitBTC!
