### ISSUE TITLE
Problem with example_rest.py file

### ISSUE THREAD

**Issue by suroegin** [hitbtc-com/hitbtc-api#149]
Hello!

I copied this file, put my API key and secret, and after commands below I got error code 1003. Please correct this example file. I don't know what I must do for normal work.

```python
class Client(object):
    ...

public_key = "..."
secret = "..."

client = Client("https://api.hitbtc.com", public_key, secret)
client.get_account_balance()
```

**Error 1003**:

```json
{"error": {"code": 1003,
  "description": "",
  "message": "Action is forbidden for this API key"}}
```

With regards,
Ivan

**Comment by fujiapple852** [comment]
Sounds like you forgot to tick “Order book, History, Trading balance” when creating your API key?

**Comment by suroegin** [comment]
@fujiapple852 I won't use them all, I want just to get balance info.

**Comment by fujiapple852** [comment]
@suroegin it appears to be all-or-nothing, if you want to be able to retrieve balance data you need this option when creating the api key.
