### ISSUE TITLE
/api/2/order error

### ISSUE THREAD

**Issue by Huanshui** [hitbtc-com/hitbtc-api#151]
api url:url = https://api.hitbtc.com/api/2/order

头文件：
"Content-Type: application/x-www-form-urlencoded"
"authorization: Basic ODVhMDEzMDQ5MzVmNWNiNzc3OTAwM2E2ZmI4YjA4MzY6OWU0OWVjNWEwNGZmMGEwNTZlNjVkYzXXXXXXXXXXXXXX="
"accept: application/json"

请求参数：
{
    price = "0.498800000";
    quantity = "1.0";
    side = sell;
    symbol = XRPUSDT;
    timeInForce = GTD;
    type = limit;
}

返回
{"error":{"code":2001,"message":"Symbol not found","description":"Try get /api/2/public/symbol, to get list of all available symbols."}}

我确定我传递了symbol，为什么提示返回symbol not found？？

**Comment by hitbtc-com** [comment]
Hi @Huanshui
You should check with list of available symbols /api/2/public/symbol . XRPUSDT -> XRPUSD
thx
