### ISSUE TITLE
BOSCoin deposit and withdrawal

### ISSUE THREAD

**Issue by 2ge** [hitbtc-com/hitbtc-api#154]
Hi,

when BOS will be possible to deposit and withdraw ? Today is 2018-04-16, Tokennet was launched at
2018-10-31 https://medium.com/@boscoin/tokennet-launch-764c7a21c77 - that means approx 5 months ago.

Also it is not really possible to find support on hitbtc (real support, not support articles), forums are closed.

Thanks

**Comment by hitbtc-com** [comment]
Dear @2ge,
We have no estimated time of BOS being available for deposit or withdrawal.
You can monitor the status of the currency here: https://hitbtc.com/system-health
