### ISSUE TITLE
Suggestion for api/2/public/symbol call

### ISSUE THREAD

**Issue by DanielFragaBR** [hitbtc-com/hitbtc-api#16]
Regarding the api/2/public/symbol call, it would be nice if you add the following fields:

- withdrawal_fee (or flat_fee from the "Fund" page)

- name of the coin (Bitcoin, Litecoin, Dash etc)

	Thanks!

**Comment by DanielFragaBR** [comment]
Anyone?

**Comment by hitbtc-com** [comment]
to get info about coin try https://api.hitbtc.com/api/2/public/currency/ETH
{
  "id": "ETH",
  "fullName": "Ethereum"
}

withdrawal_fee will try to provide. 
You can try also view withdrawal info before commit it, using 2 phase commit.
Also you can send amount including fee or not.

Try it at https://api.hitbtc.com/api/2/explore/

**Comment by georgewalther** [comment]
Thanks
