### ISSUE TITLE
How can I bring withdrawal fees down?

### ISSUE THREAD

**Issue by keyonoyek** [hitbtc-com/hitbtc-api#162]
I want to withdraw 1600 atm to send to a friend. Hitbit wants to charge me 3333 tokens to send it! I want to send 2000 STORM to my hardware wallet. Htbtc wants 400 of them to 'allow.'

I am not a wealthy magnate of commerce. I am not the facilitator of your dreams if you make this impossible. I am but one person who came here with good intentions and I do not know how this could profit me. How do I remove myself without pain? Am I trapped? Did I make a mistake in coming here? There has to be a better way. 
hugggggggggs@gmail.com

**Comment by hitbtc-com** [comment]
Most of the coins required network fees

**Comment by keyonoyek** [comment]
What? I regret the day I registered. Now, how do I escape with what I have?
I will be sharing my experience. I hope you do not steal the rest,
