### ISSUE TITLE
'Currency operations not available'' and KYC, submission of fund evidence documents

### ISSUE THREAD

**Issue by RYUcomet** [hitbtc-com/hitbtc-api#165]
I want to talk about my ticket number # 283006.
At first my BTC was unable to make a deal.
So I sent you the tickets with all of the material that was required by the .C, source of funding, and HITBTC.
However, no reply has been received yet. This problem should be solved quickly and I hope you will be busy, but you can read me my ticket.
Have a good day.

**Comment by hitbtc-com** [comment]
Dear @RYUcomet,
I believe your account was already verified. Enjoy trading with HitBTC!
