### ISSUE TITLE
Got locked ! "Currency operations not available" can't withdraw or trade!

### ISSUE THREAD

**Issue by MajZoa** [hitbtc-com/hitbtc-api#167]
I transferred BTC from Binance to HitBTC then tried to transfer back to the same address to Binance. Got locked! "Currency operations not available"
Ticket ID #289353 please please look into this!

**Comment by hitbtc-com** [comment]
Dear @MajZoa,
I believe your account was successfully verified.
Enjoy trading with HitBTC!
