### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by rdmnnn** [hitbtc-com/hitbtc-api#168]
Mistakenly deposited SPF to ETH address
Ticket ID #273590

**Comment by iliyabit** [comment]
i have next token in the time of airdrop for ignis but i did not  receive  my ignis yet .i sent some ticket a bout that problem but admins wont answer and solve . would you please answer when i receive my ignis

**Comment by rdmnnn** [comment]
40 days was not answered

**Comment by rdmnnn** [comment]
I accidentally sent an ethereum address to an ethereum token spf

**Comment by hitbtc-com** [comment]
Dear @rdmnnn,
I believe your issue was successfully resolved. Enjoy your trading with HitBTC!
