### ISSUE TITLE
Wrong quantity in Cancel Response

### ISSUE THREAD

**Issue by Serpens66** [hitbtc-com/hitbtc-api#17]
The Cancel Order API v2 response for an unfilled order looks like this:

{'price': '0.010000', 'type': 'limit', 'cumQuantity': '0.000', 'symbol': 'ETHBTC', 'quantity': '0.000', 'updatedAt': '2017-06-14T21:03:44.339Z', 'clientOrderId': '0e10b547b44cbddd0ebf5978579ea978', 'createdAt': '2017-06-14T20:57:55.045Z', 'id': '1124907085', 'side': 'buy', 'timeInForce': 'GTC', 'status': 'canceled'}

And the cancel response of an order were 5 out of 6 were filled:
{'price': '0.00048450', 'cumQuantity': '5.0', 'status': 'canceled', 'clientOrderId': '3d86f695c9c228f5178d6e872c910595', 'side': 'buy', 'quantity': '5.0', 'symbol': 'EMCBTC','timeInForce': 'GTC', 'id': '1125961609', 'createdAt': '2017-06-14T23:57:04.007Z', 'updatedAt': '2017-06-14T23:57:04.283Z', 'type': 'limit'}

In both cases, the quantity is wrong, assuming it should show the amount which the order was placed.
In case this is intended, you have to add a new entry called "originalamount" or simular.

**Comment by hitbtc-com** [comment]
FIXED
