### ISSUE TITLE
HitBTC, help. Currency operations not available

### ISSUE THREAD

**Issue by stasenko** [hitbtc-com/hitbtc-api#171]
Guys, HitBTC, I've already wrote to You, pls, help. All my coins are "Currency operations not available".
Support Ticket ID #291774 and Ticket ID #290999. I'm waiting more than 48 hours for an answer from You.
Thank You.

**Comment by stasenko** [comment]
My support Ticket ID #291774 and Ticket ID #290999.
All my coins in "Currency operation not available". I've already send KYC documents 2 days ago.
Really need money now.

**Comment by stasenko** [comment]
My all coins locked - "Currency operations not available".
I left two tickets in support - Ticket ID #291774 and Ticket ID #290999.
I wrote two times for verification on compliance@hitbtc.com, send my passport, bank card and photo of me with PC's hitbtc.com.
Only result I have 64 hours on reddit hitbtc wrote that I need go to verification, but I already gone to verification.
I have no choice only go to legal advisors :(

**Comment by stasenko** [comment]
u/hitbtc, finally, I have answer from support after 4 days of awaiting that I need go to KYC - send photo of ID and selfie. I do this and wait of relock.

**Comment by stasenko** [comment]
u/hitbtc, guys. My support ticket #290999. I'm week - more than 7 days on currency operations not available. 3 days ago I have answer from support that I need send photo of ID and selfie with ticket, and I immediately do this. How long I should wait for relock?

**Comment by stasenko** [comment]
u/hitbtc, thank You for your response. My account is deactivated at 14.07.2018 - verification process was started

**Comment by hitbtc-com** [comment]
Thank you for the information sent, @stasenko - you'll be provided with a follow-up in the ticket once there's an update.
