### ISSUE TITLE
Help my life please

### ISSUE THREAD

**Issue by riniky** [hitbtc-com/hitbtc-api#172]
Dear HitBTC,

Please, my account shows 'currency operation not available'... Both my children die on a car accident, after that, coin is the only thing to keep me alive (to help me not to cry everyday)... now all my coin blocked by this 'currency operation not available', i'm nearly crashed... please help me, i'm a such good person, never do anything bad, this thing should not happen on me... please please.... my ticket number is:  #293076   , please.... my life is in your hand, seriously...

**Comment by pigslayer12** [comment]
you should post in the subreddit or on their twitter. hope things get better man, stay strong, its what your kids would've wanted :)

**Comment by riniky** [comment]
no reply on ticket, email, and no phone available... send so many on facebook, twitter, no reply... when i start with small amount, everything is fine, but when i transfer all i have to hitbtc, my money is blocked.... i search google, so many people are blocked months unsolved... i don't know if I can stay on this matter, im totally crashed... pls, if anybody know them, please please tell them to save my life before too later, i cant stay such tension every day

**Comment by hitbtc-com** [comment]
Dear @riniky,
Your account is now verified and you are welcome to trade on HitBTC on a regular basis.
We are sorry for your loss and sincerely hope things will get better with time.
