### ISSUE TITLE
Currency operations not available - support ticket #290999

### ISSUE THREAD

**Issue by stasenko** [hitbtc-com/hitbtc-api#173]
hitBTC, guys. My support ticket #290999. I'm week - more than 7 days on currency operations not available. 3 days ago I have answer from support that I need send photo of ID and selfie with ticket, and I immediately do this. How long I should wait for relock?

**Comment by stasenko** [comment]
u/hitbtc, thank You for your response. My account is deactivated at 14.07.2018 - verification process was started.

**Comment by martin-g** [comment]
> My account is deactivated at 14.07.2018

you come from the future, man!
what is the BTC price ? should I buy or sell ?
