### ISSUE TITLE
The funds disappeared.

### ISSUE THREAD

**Issue by hajaeyong** [hitbtc-com/hitbtc-api#175]
My ETH has disappeared from the transaction to the main account. Please check!

**Comment by ManuelSchneid3r** [comment]
Look hun, this is an issue tracker for software. You made an accout to load of your shit here. Do you really expect to get an answer?

**Comment by hitbtc-com** [comment]
Thank you for your inquiry!
Have you contacted our support team regarding the issue? If not, you can do so right here: https://support.hitbtc.com/hc/en-us/requests/new?ticket_form_id=360000030449 in order for us to help you. Thanks in advance!
