### ISSUE TITLE
Deposit issue pending 8th may 2018

### ISSUE THREAD

**Issue by Moolchandsharma** [hitbtc-com/hitbtc-api#178]
Dear sir, I deposit my bch quantity 1.009 at hitbtc bch account but no received yet after daily created ticket but no reply , I have checked my address match taken from hitbtc bch deposit .so pl solve my issue also my fund value also decrease. What I do 
I think hitbtc team not respond
Moolchandsharma

**Comment by ManuelSchneid3r** [comment]
Offtopic?

**Comment by hitbtc-com** [comment]
Dear @Moolchandsharma, 
Please share your ticket number in the comments in order to provide us with a follow-up.
