### ISSUE TITLE
 ignis airdrop problem 

### ISSUE THREAD

**Issue by iliyabit** [hitbtc-com/hitbtc-api#182]
i have next in the time of airdrop for ignis but i did not receive my ignis yet .i sent some ticket a bout that problem but admins didnt answer and solve . would you please answer when i receive my ignis

**Comment by ManuelSchneid3r** [comment]
Is that related to the api?

**Comment by iliyabit** [comment]
I dont think so . i dont know what is the problem and why the support team dose not answer clearly

**Comment by ManuelSchneid3r** [comment]
Because this is not support here. This is an issue tracker.

**Comment by hitbtc-com** [comment]
Thanks for reaching out, @iliyabit!
Can you please provide us with your ticket number? Thanks in advance!

**Comment by iliyabit** [comment]
hello and thanks for your attention . i find out that my problem dosent
related to the subjest . can you help me where can i bring up my problem
and who should i speak with?

**Comment by hitbtc-com** [comment]
Sure thing!
You can contact our support team right here: https://support.hitbtc.com/hc/en-us in order for us to help you.
