### ISSUE TITLE
WS API not sending updateOrderbook messages

### ISSUE THREAD

**Issue by WillHern91** [hitbtc-com/hitbtc-api#183]
Hello, when I connect to the WS API and subscribe to "subscribeOrderbook" feed, I only receive the initial "snapshotOrderbook". I do not get any "updateOrderbook" afterwards and the feed just goes stale.  This was working like expected up until today.

**Comment by fxsession** [comment]
Same story with WS API v2. On top of that I don't receive updates for candles and trades.

**Comment by WillHern91** [comment]
To clarify, I am also on WS API v2.  This is also happening when I subscribe to the ticker feed.  I get the first "ticker" message, but I do not get any more after than.

**Comment by fxsession** [comment]
They fixed it.Poor support :-1:  no notifications, nothing about the issues in the core engine. I'm disappointed :(
