### ISSUE TITLE
no response from hitbtc regarding tiokens sent to wrong place

### ISSUE THREAD

**Issue by nagemnoiff** [hitbtc-com/hitbtc-api#187]
2 weeks ago today, i foolishly sent some link tokens to the erc20 token wallet address associated to my account
I  contacetd Hitbtc and got their standardaised message back but nothing else since
Am i right in thinking that although they don't support the token they should be able to send back out as the private key for my erc20 wallet will be the same no matter what erc20 coin it is
This should be a straight forward issue in my opinion and I can't believe that hitbtc are taking so long to contact me back
Any help would be appreciated

**Comment by ManuelSchneid3r** [comment]
How is that related to the api? Maybe they need the time because they have shitloads questions like that in places like this.
