### ISSUE TITLE
Suggestion: Withdrawal/Deposit halted

### ISSUE THREAD

**Issue by Serpens66** [hitbtc-com/hitbtc-api#19]
Please add somewhere the information, if deposit/withdrawal for a currency is possible at the moment.

I think at the moment the only way to find out, is to make a withdrawal request and get an error.
But I would like to know before, so if withdrawals are disabled, I won't buy this currency meanwhile.

**Comment by hitbtc-com** [comment]
Provide soon

**Comment by hitbtc-com** [comment]
Explore at https://api.hitbtc.com/api/2/explore/
example call "https://api.hitbtc.com/api/2/public/currency/eth"

with response:

{
  "id": "ETH",
  "fullName": "Ethereum",
  "crypto": true,
  "payinEnabled": true,
  "payinPaymentId": false,
  "payinConfirmations": 2,
  "payoutEnabled": true,
  "payoutIsPaymentId": false,
  "transferEnabled": true
}

**Comment by lvhf1971** [comment]
我要退这个邮件，怎么退？不再接收






发自网易邮箱大师


On 10/7/2017 00:07，hitbtc-com<notifications@github.com> wrote：

Explore at https://api.hitbtc.com/api/2/explore/
example call "https://api.hitbtc.com/api/2/public/currency/eth"

with response:

{
"id": "ETH",
"fullName": "Ethereum",
"crypto": true,
"payinEnabled": true,
"payinPaymentId": false,
"payinConfirmations": 2,
"payoutEnabled": true,
"payoutIsPaymentId": false,
"transferEnabled": true
}
