### ISSUE TITLE
Cannot Send payload - Connection not established!

### ISSUE THREAD

**Issue by a5601564** [hitbtc-com/hitbtc-api#190]
Cannot Send payload - Connection not established!

**Comment by hitbtc-com** [comment]
Hi @a5601564 

If problem not solved, please provide more information about error (language, code example)

**Comment by hitbtc-com** [comment]
see example https://gist.github.com/hitbtc-com/fc738c1b926d9d7aa7e3bd5247f792a1

**Comment by monster1616** [comment]
import time
import queue
from hitbtc import HitBTC
c = HitBTC()
c.start()  # start the websocket connection
time.sleep(2)  # Give the socket some time to connect
c.subscribe_ticker(symbol='ETHBTC') # Subscribe to ticker data for the pair ETHBTC

while True:
    try:
        data = c.recv()
        
    except queue.Empty:
        continue

    # process data from websocket
    

c.stop()

Error: Cannot Send payload - Connection not established!

**Comment by StelicaRusu** [comment]
Set a higher value for time.sleep() and it works just fine
