### ISSUE TITLE
Suggestion: Secure API withdrawal

### ISSUE THREAD

**Issue by Serpens66** [hitbtc-com/hitbtc-api#20]
I already wrote this to HitBTC support weeks ago, but they usually do not answer to things like this...
Not sure if this is API related or website related, but I feel here I will get more likely an answer.

I would like to see additional security for API withdrawal.
Eg. a whitelist, where you can add several addresses per currency. You add them manually in your hitbtc settings and confirm them by 2FA and/or Email.
Then allow the API only to withdraw to those whitelist addresses (if whitelist was set up from the user).

**Comment by dparlevliet** [comment]
+1

**Comment by dparlevliet** [comment]
ip whitelisting for api keys is important

**Comment by hitbtc-com** [comment]
Security is important.
We are working on this to provide this functionality within 2 months.

**Comment by Serpens66** [comment]
Hi,
Seems you officially released API v2. 
Is the withdrawal security already integrated? I read something about "two phase comit", but what is it? Is it for security or is it something else? If it is not, what will you implement for secure API withdrawal?

**Comment by hitbtc-com** [comment]
white list for withdraw in progress
"two phase commit" - 1 call create withdraw. 2 call commit it or rollback. it allow you make withdraw only once for example

**Comment by Graal46** [comment]
?

**Comment by PWCB** [comment]
I don't see an option to enter an IP address. At this point I can still have all of my currency stolen by someone with trading permissions via the API.

**Comment by Gkathuria2** [comment]
My XEM withdrawal is pending from last 60 hours

Operational id is a58bd9db-2f8f-44f7-b585-dd94913b6712

kindly check these tickets #251471
#251092

Now XEM is offline on receiving address, please cancel withdrawal request and add fund back.

@HitBTC_Support_Team

**Comment by hitbtc-com** [comment]
White list  is available for withdrawal
