### ISSUE TITLE
WebSocket Read EOF

### ISSUE THREAD

**Issue by fxsession** [hitbtc-com/hitbtc-api#203]
Hi,
I get "WebSocket Read EOF" message regularly in 1-2 hours after I setup a secure connection. why? Insecure connection working in parallel keeps alive.

**Comment by fxsession** [comment]
No response. Great support!

**Comment by fxsession** [comment]
The number of disconnects increased significantly. 1006 (EOF) and 502(Bad Gateway) occur almost every 2-3 minutes. It's impossible to trade. 
Are you serious when you declare on your start page "HitBTC is delivering the most reliable, fast and powerful platform solution on the market."?

**Comment by WillHern91** [comment]
Same issue here.  Both my Python and C++ systems had been running ok up until a few weeks ago.  They began disconnecting every couple of hours, but now it is happening every few minutes.

**Comment by fxsession** [comment]
Support has replied recently that they had  launched a new update for API. I noticed that the amount of disconnecting reduced a little bit but still they occur every 5-10 minutes which  is not acceptable.
Attaching snapshot of wireshark dump which clearly shows that the server initiates disconnecting.
![tcptrace-fin](https://user-images.githubusercontent.com/4971320/45366135-cced2800-b5e6-11e8-8af5-a488bed8a5f0.jpg)

**Comment by fxsession** [comment]
I did the same thing but it's far from HFT when you need to reconnect... temporary switched to binance though fees are higher.

**Comment by hitbtc-com** [comment]
You application should subscribe once, and fetch data from socket fast.
If you try subscribe unsubscribe and again, then your requests will be rate limited.
If you can't fetch fast data from the socket, then your connection will be closed. If you too often was slow, then your IP will be banned for an hour.
