### ISSUE TITLE
Websocket API Disconnects

### ISSUE THREAD

**Issue by jsveto** [hitbtc-com/hitbtc-api#206]
I get regular disconnects initiated from server side when using websocket API. To reproduce the bug:

1.) Connect to websocket
2.) Subscribe to orderbook
3.) Wait

Sooner or later orderbook updates stop and disconnect is initiated by server soon after. The time when orderbook updates stop coming varies from 30s to several hours. I have tried same example from several IP addresses with stable internet connection. I have tried same thing with different websocket implementation libwebsockect(C/C++), wscat, WebSocket(java).

Is this known problem and what is ETA for fix?

Regards,
jsveto

**Comment by HotRamen** [comment]
Same problem here ...

**Comment by grhangelone** [comment]
Yep, It's 2 days now

**Comment by WillHern91** [comment]
I too am experiencing this using both Python websockets and websocketpp (C++ library).  These systems had been running without issue for months until a few weeks ago.  Disconnects started little by little and are now happening every few minutes at this point.

**Comment by nateonthenet** [comment]
Same problem.

**Comment by tradadi** [comment]
We're seeing the same problem. Would appreciate an update.

**Comment by mainkai** [comment]
Same here. I've wasted hours debugging my code and hunting for a bug that was never on my side.
Please fix ASAP.
Currently, HitBTC is completely useless to me.

Btw, these threads seem to address the same problem:
https://github.com/hitbtc-com/hitbtc-api/issues/207
https://github.com/hitbtc-com/hitbtc-api/issues/203

**Comment by hitbtc-com** [comment]
You application should subscribe once, and fetch data from socket fast.
If you try subscribe unsubscribe and again, then your requests will be rate limited.
If you can't fetch fast data from the socket, then your connection will be closed. If you too often was slow, then your IP will be banned for an hour.
