### ISSUE TITLE
Suggestion: Improve "Order Status" call

### ISSUE THREAD

**Issue by Serpens66** [hitbtc-com/hitbtc-api#21]
It happens frequently, that I place an order and 5 seconds later I would like to check, if the order is filled or not.
Therefore I do first the call "order/:ID". (REST API v2)

But here the problem is, that when the order is already cancelled or completely filled I get "not found" error message. So my bot can not be 100% sure what the status of the order is (cause when timeout happens during a cancel call, the order could be filled or cancelled).

So if this returns "not found" I do the "history/order" call to find out about the order.
But here the problem is, that this only updates rarely. According to documentation it should update every 30 seconds? But I always wait up to 60 seconds and the order is mostly not found...

So the best you can do is to also return filled orders with your order/:ID call. For cancelled+completely unfilled orders you can return "not found". But if an order was partly filled and cancelled I also need a response.

edit:
"not found" could also mean, that the order was never there. Eg. when your engine is too slow (so it was not even placed yet. Unfortunately this happens for half of all big exchanges in high volume times like this) Or it could mean I entered a wrong ID.
So there are too many meanings of "not found".

**Comment by hitbtc-com** [comment]
Currently we reduced update history till to 1 sec
