### ISSUE TITLE
Getting trade history for CLBTC (Coinlancer/Bitcoin) symbol through API

### ISSUE THREAD

**Issue by pjboro** [hitbtc-com/hitbtc-api#210]
Hi, guys.
It's great you have a github account and provide a python module for communication with your exchange. Thanks for all the work!

I'm writing here, because I have troubles obtaining history of trades concerning Coinlancer cryptocurrency. It was available on HitBTC in January and it was made unavailable some time ago. I've tried using ccxt hitbtc2 module, https://github.com/pulkit1991/hitbtcapi , and https://api.hitbtc.com/api/2/explore/ with the same result: I see no way to get the trades.
Everything was done on docker python:3 image with ccxt and hitbtcapi installed using pip.
```
client.get_trades('ETHBTC') # this works perfectly
# python prints the list of trades for ETHBTC
client.get_trades('CLBTC') # this one, sadly, not so much
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/hitbtcapi/client.py", line 122, in get_trades
    return self._handle_response(response)
  File "/usr/local/lib/python3.7/site-packages/hitbtcapi/client.py", line 67, in _handle_response
    raise api_response_error(response)
hitbtcapi.errors.InvalidRequestError: 400 Symbol not found (Try get /api/2/public/symbol, to get list of all available symbols.)
```
How can I resolve this?

Best regards,
pjb

**Comment by hitbtc-com** [comment]
You can't get trading history for closed market
