### ISSUE TITLE
hitBTC wrong fee information

### ISSUE THREAD

**Issue by ticketself** [hitbtc-com/hitbtc-api#212]
"On HitBTC, "Takers" are charged with 0.1% fee from the trade. "Makers" are not charged with a fee. On the contrary, they receive a 0.01% rebate from the trade."

https://hitbtc.com/fees-and-limits

I want my fee charges back, you are charging 0.09% in my maker trading.

**Comment by hitbtc-com** [comment]
Can you provide your trade id?
