### ISSUE TITLE
Method 'order ' always returns 'Symbol not found'

### ISSUE THREAD

**Issue by stefanbu** [hitbtc-com/hitbtc-api#214]
Using the REST API v2 works without problems for me, with one important exception with the method 'order'. I am not able to place a trade.

I always get back this (independent of the used parameters):
{"error":{"code":2001,"message":"Symbol not found","description":"Try get /api/2/public/symbol, to get list of all available symbols."}}

Example -URL:
"https://api.hitbtc.com/api/2/order?symbol=ETHBTC&side=buy&type=limit&timeInForce=GTC&quantity=0.1&price=0.02"

Code:
HTTPMethod="POST"
URL = "https://api.hitbtc.com/api/2/order?symbol=ETHBTC&side=buy&type=limit&timeInForce=GTC&quantity=0.1&price=0.02"

' Instantiate a WinHttpRequest object and open it
Set objHTTP = CreateObject("WinHttp.WinHttpRequest.5.1")

objHTTP.Open HTTPMethod, URL, False
objHTTP.setRequestHeader "User-Agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)"
objHTTP.setRequestHeader "accept", "application/json"
objHTTP.setRequestHeader "Content-Type", "application/x-www-form-urlencoded"
objHTTP.setRequestHeader "Authorization", "Basic " & Base64Encode(apikey & ":" & secretkey)
objHTTP.Send ("")

objHTTP.WaitForResponse
PrivateHitBTC2 = objHTTP.ResponseText
Set objHTTP = Nothing

**Comment by hitbtc-com** [comment]
You have to send data 'symbol=ETHBTC&side=buy&type=limit&timeInForce=GTC&quantity=0.1&price=0.02' as payload on POST or PUT request. 
See curl & python example at doc https://api.hitbtc.com/#create-new-order

**Comment by filinvadim** [comment]
They're forgot about header "Content-Type: application/x-www-form-urlencoded" .
Terrible API.
