### ISSUE TITLE
Candles via api endpoint

### ISSUE THREAD

**Issue by dparlevliet** [hitbtc-com/hitbtc-api#22]
Currently it seems the only way to get candle data is via the websocket and even that is very limited. Can we get a proper candle endpoint with date range select?

**Comment by SydorukAndrii** [comment]
I also want to hear the answer.

**Comment by SydorukAndrii** [comment]
How does this site work? There may be an undocumented API?

https://min-api.cryptocompare.com/data/histominute?fsym=XEM&tsym=BTC&limit=20&aggregate=1&e=HitBTC

**Comment by hitbtc-com** [comment]
Now there is no such api
Let's try to provide

**Comment by SydorukAndrii** [comment]
Ok

**Comment by hitbtc-com** [comment]
explore on https://api.hitbtc.com/api/2/explore/
example https://api.hitbtc.com/api/2/public/candles/ETHBTC?limit=100&period=M30

**Comment by hitbtc-com** [comment]
currently no data range selector provided

**Comment by osascruz** [comment]
This is a bit confusing,  is the timestamp  UK BTS time or GMT time ?
also it seems that the samples are not with fixed timestamp ...  I tried 
https://api.hitbtc.com/api/2/public/candles/VERIBTC?limit=1000&period=M5
got 
2017-10-24T00:35:00.000Z
2017-10-24T00:50:00.000Z
2017-10-24T01:30:00.000Z
....
2017-10-24T04:55:00.000Z
which is not constant step. 
Also seems like last sample is old by more than 1h   .. here 4h55  while GMT is 5h32 

I tried to match samples with 
https://min-api.cryptocompare.com/data/histominute?fsym=VERI&tsym=BTC&limit=1000&aggregate=5&e=HitBTC
but no real success.

**Comment by hitbtc-com** [comment]
Z mean GMT time. see https://en.wikipedia.org/wiki/ISO_8601
doc https://github.com/hitbtc-com/hitbtc-api/blob/master/APIv2.md#candles
Result contain candles only with non zero volume
