### ISSUE TITLE
My coins are being held hostage for no reason!

### ISSUE THREAD

**Issue by JTmon3y** [hitbtc-com/hitbtc-api#238]
I went to withdraw my BTC and it was halted.  I found out they wanted me to fill out more KYC which I promptly did so.  This included updating my KYC photos plus a utility bill, social media account, and a transaction hash history.  I am still waiting for them to approve me.

Today I wanted to at least place my coins into a stable coin while I am waiting for them to reply only to realize my trading has been frozen!!  This is unacceptable and could end up costing me THOUSANDS of dollars!!

My ticket ID is 439914

Please at least allow me to trade while I am waiting so I don't lose a huge part of my money.  I have done everything they have asked of me so far.

**Comment by hitbtc-com** [comment]
Sorry for the delayed reply. You have successfully completed KYC/AML verification, your HitBTC account is perfectly functional.
