### ISSUE TITLE
Suggestion: withdraw payment_id applied to "message" (NXT, XEM etc)

### ISSUE THREAD

**Issue by DanielFragaBR** [hitbtc-com/hitbtc-api#24]
It would be nice if the /api/2/account/crypto/withdraw paymentId parameter could be used to provided a "message" for NXT based coins (and XEM and others which use "message" instead of "payment_id").

**Comment by hitbtc-com** [comment]
There is no point in expanding the glossary of terms. This can be misleading.
Currently NXT coin based not supported "message".
