### ISSUE TITLE
'code': 20008, 'message': 'Duplicate clientOrderId' on cancelOrder

### ISSUE THREAD

**Issue by alexanderborsch** [hitbtc-com/hitbtc-api#242]
Getting this error for a few months now:
{'method': 'cancelOrder', 'params': {'clientOrderId': '1234567890123456789'}, 'id': 1590123456789} 
{'jsonrpc': '2.0', 'error': {'code': 20008, 'message': 'Duplicate clientOrderId', 'description': 'ClientOrderId must be unique during trading session'}, 'id': 1590123456789}
Obviously the ID is not unique as I'm trying to cancel an existing order.

**Comment by hitbtc-com** [comment]
For the cancel Order request, you can't get a duplicate error message, looks like that you have got a response for different requests with the same id.
Seem that you use a timestamp in ms as the id for your purpose.
better to use atomic increase counter for this, if this is not available then guid can be a good choice

Do you use new endpoint wss://api.hitbtc.com/api/2/ws/trading ?

**Comment by alexanderborsch** [comment]
Exactly.
I'm pretty sure that the error comes in response to a cancelOrder request.
For id use "int(10000 * time.time())" which increments every 100 microseconds and this is irrelevant as the error clearly says "Duplicate clientOrderId" not "Duplicate id".
I use wss://api.hitbtc.com/api/2/ws as suggested here: https://api.hitbtc.com/#api-urls.

**Comment by alexanderborsch** [comment]
Just switched to using guid for id, still getting the error

**Comment by hitbtc-com** [comment]
Anyway use the new endpoint, official documentation have to be updated soon.
By code, do you use a Golang? If possible you can attach here this part of code?

**Comment by alexanderborsch** [comment]
'wss://api.hitbtc.com/api/2/ws/trading' doesn't work

**Comment by alexander-hagen** [comment]
> Exactly.
> I'm pretty sure that the error comes in response to a cancelOrder request.
> For id use "int(10000 * time.time())" which increments every 100 microseconds and this is irrelevant as the error clearly says "Duplicate clientOrderId" not "Duplicate id".
> I use wss://api.hitbtc.com/api/2/ws as suggested here: https://api.hitbtc.com/#api-urls.

I have the same error: 
{"method":"cancelOrder","params":{"clientOrderId":"M-200531211307783-D-008"},"id":705}

### Error caught (cancelOrder): {"code":20008,"message":"Duplicate clientOrderId","description":"ClientOrderId must be unique during trading session"}
DEL: M-200531211307783-D-008

**Comment by alexander-hagen** [comment]
I have reduced clientOrderID to 20 characters and there's no duplicate clientOrderId errors anymore.

**Comment by alexanderborsch** [comment]
Tried reducing it to 20 chars now, didn't help.
I'm getting the error on cancel only though.

**Comment by alexanderborsch** [comment]
Looks like this error happens only when I cancel orders that previously failed to update by the server:
debug {'method': 'cancelReplaceOrder', 'params': {'clientOrderId': '**D1jjawehAR2am2zQ1128**', 'requestClientId': 'gwhpykBN3owdrGt8cQ65', 'quantity': '1.00000000', 'price': '0.000214091'}, 'id': 384967} {'jsonrpc': '2.0', 'error': {'code': 500, 'message': 'Internal Server Error', 'description': ''}, 'id': 384967}
debug {'method': 'cancelOrder', 'params': {'clientOrderId': '**D1jjawehAR2am2zQ1128**'}, 'id': 386775} {'jsonrpc': '2.0', 'error': {'code': 20008, 'message': 'Duplicate clientOrderId', 'description': 'ClientOrderId must be unique during trading session'}, 'id': 386775}

**Comment by alexanderborsch** [comment]
still not resolved

**Comment by alexanderborsch** [comment]
I give you valid bug reports, not some "hitbtc scam" comments, and you just ignore them.
It's hard to use the API when you get unexpected errors every tenth request.
