### ISSUE TITLE
1

### ISSUE THREAD

**Issue by alexanderborsch** [hitbtc-com/hitbtc-api#244]

**Comment by alexanderborsch** [comment]
still not resolved

**Comment by hitbtc-com** [comment]
Hello,  alexanderborsch 

Please try new endpoint: wss://api.hitbtc.com/api/2/ws/trading
New endpoint also support margin trading.

**Comment by alexanderborsch** [comment]
Hi,

Tried the endpoint previously, tried it again now: doesn't work.
Gives me "{"jsonrpc":"2.0","error":{"code":404,"message":"Method not found"}" to any request.

Thanks,
Alex

**Comment by hitbtc-com** [comment]
Hello, Alex.

Note please that wss://api.hitbtc.com/api/2/ws/trading used for private trading (place orders, margin trading, get balance, and so on)

Public endpoints used only for subscribing to market data (orderbook, trading, tickers): wss://api.hitbtc.com/api/2/ws/public  and wss://api.hitbtc.com/api/2/ws

**Comment by alexanderborsch** [comment]
Ok, but why do I get the 403 when try to connect wss://api.hitbtc.com/api/2/ws/public?
