### ISSUE TITLE
Insufficient funds error when funds are sufficient error

### ISSUE THREAD

**Issue by etalazz** [hitbtc-com/hitbtc-api#246]
Hello,

I get an **"Insufficient funds","description":"Check that the funds are sufficient, given commissions"** error when I try to withdraw my money

Here's the API end point :

 "https://api.hitbtc.com/api/2/account/crypto/withdraw" \
    -d 'currency=USD&amount=391.38&address=xxx&autoCommit=true'

The Account is well funded under USDT.

Does anybody know what's happening?

**Comment by hitbtc-com** [comment]
Hello,
Please check that the required amount is on the account balance, not on the trading.
Or provide more information using the service desk.
