### ISSUE TITLE
EMGO MobileGo balance not returned in /api/1/trading/balance response

### ISSUE THREAD

**Issue by donovanhide** [hitbtc-com/hitbtc-api#25]
Hi, 
I seem to get most of my balances in the  `/api/1/trading/balance`  response but EMGO is not one of them! Is this a bug, or am I missing something obvious?

Cheers!

**Comment by asavis** [comment]
Some other currencies are also missing: PRG, CND, BMC.

**Comment by donovanhide** [comment]
Any update on this? It makes it hard to correctly reconcile available and reserved balances when applying execution reports locally.

**Comment by donovanhide** [comment]
Ping :-) This is really important. How can I know what balances I have otherwise?

**Comment by donovanhide** [comment]
In case anyone stumbles on this, the problem is fixed in V2.

**Comment by asavis** [comment]
Where do I find v2 docs?

**Comment by donovanhide** [comment]
In this repo:

https://github.com/hitbtc-com/hitbtc-api/blob/master/APIv2.md

**Comment by hitbtc-com** [comment]
FIXED
