### ISSUE TITLE
Account Verification Issue

### ISSUE THREAD

**Issue by car7563** [hitbtc-com/hitbtc-api#254]
After sending my KYC data and selfie they are now saying there is an issue with my verification selfie.They can't accept it due to poor image quality even though the photo quality is the highest quality resolution that any phone can offer.They add "If your phone or camera can only take low quality photos you may have to find a better camera".

I am using the latest samsung phone available and bought it because it has such a great camera??? This is getting ridiculous.

**Comment by Fixer777** [comment]
HitBTC is a SCAM, I withdraw 0.001 BTC from my account with them and only received 0.0001 BTC. I'm trying to contact them for 2 weeks now, but no response.

**Comment by car7563** [comment]
I managed to have the KYC done after second attempt so this issue is now resolved.
