### ISSUE TITLE
BET arrived in wallet i dont have acess!

### ISSUE THREAD

**Issue by mnuneze** [hitbtc-com/hitbtc-api#27]
2017-08-30 15:02
Dear Team, i deposited my BET from my wallet to the created wallet for BET in HitBTC: 0xa8d0208009f327bf42019b61e66cae2404933a43

The transfer has been made various hours ago and it seems to not arrive, can you please check to see if there is any technical error as no transaction even appears on my transactions in hITbtc, Find the transaction made here as proof: https://etherscan.io/token/0x725803315519de78d232265a8f1040f054e70b98?a=0xa8d0208009f327bf42019b61e66cae2404933a43

here is the wallet showing my 6000 BET, but nothing on the platform: https://etherscan.io/address/0xa8d0208009f327bf42019b61e66cae2404933a43

Please assist me on this! Thank you.

**Comment by hitbtc-com** [comment]
You should write to support with this question
