### ISSUE TITLE
Patch order not working,

### ISSUE THREAD

**Issue by gasse4life** [hitbtc-com/hitbtc-api#277]
hi i need help to patch order,

i tried in v2 and v3,

i can cancel or put an limitMarket or stopLimit order,

but both return error 500 when i tru to patch,  anybody can help?

**Comment by hitbtc-com** [comment]
Please share request body.

**Comment by gasse4life** [comment]
https://api.hitbtc.com/api/2/explore/

PATCH /spot/order/{client_order_id}

always invalid path share or error 500, and after an error 500 if i retry i got duplicate client order id

**Comment by gasse4life** [comment]
curl -X POST "https://api.hitbtc.com/api/3/spot/order" -H "accept: application/json" -H "Authorization: Basic Z2c3X0lhQ08tZTRfSzJBcjR1M0FQd2pUaVQwMXFRSlY6SFJpd0x2S0s3Yk4yYVdfcWVJQ1lnbVFYSmQ4Zkwxang=" -H "Content-Type: application/x-www-form-urlencoded" -d "client_order_id=43fggt56677ucfvffft567uyy&symbol=XRPUSDT&side=sell&type=stopMarket&time_in_force=GTC&quantity=0.1&price=1.50000&stop_price=1.115421"



{
  "id": 704904230579,
  "client_order_id": "43fggt56677ucfvffft567uyy",
  "symbol": "XRPUSDT",
  "side": "sell",
  "status": "suspended",
  "type": "stopMarket",
  "time_in_force": "GTC",
  "quantity": "0.1",
  "quantity_cumulative": "0",
  "stop_price": "1.115421",
  "post_only": false,
  "created_at": "2021-11-10T21:49:53.933Z",
  "updated_at": "2021-11-10T21:49:53.933Z"
}




INSERT IS OKAY


now  patch


curl -X PATCH "https://api.hitbtc.com/api/3/spot/order/43fggt56677ucfvffft567uyy" -H "accept: application/json" -H "Authorization: Basic Z2c3X0lhQ08tZTRfSzJBcjR1M0FQd2pUaVQwMXFRSlY6SFJpd0x2S0s3Yk4yYVdfcWVJQ1lnbVFYSmQ4Zkwxang=" -H "Content-Type: application/x-www-form-urlencoded" -d "quantity=0.1&price=1.100000&new_client_order_id=43fggt56okokokucfvffft567uyy"




{
  "error": {
    "code": 500,
    "message": "Internal Server Error"
  }
}

**Comment by hitbtc-com** [comment]
Thank you for this report. 

Unfortunately, order Cancel/Replace is not supported for suspended (stop) orders. Once supported, you will know it from Change Log section in the API documentation.
Error 500 will be replaced by 400 with description.

**Comment by gasse4life** [comment]
ok thank you for your help and very fast reply, 

i hope it will be soon..

its pulling a tons of request to the server for nothing,

maybe you can tip me to reduce request,

is there any type of trade i can patch?

**Comment by hitbtc-com** [comment]
Any active limit order can be replaced.

**Comment by gasse4life** [comment]
curl -X POST "https://api.hitbtc.com/api/3/spot/order" -H "accept: application/json" -H "Authorization: Basic Z2c3X0lhQ08tZTRfSzJBcjR1M0FQd2pUaVQwMXFRSlY6SFJpd0x2S0s3Yk4yYVdfcWVJQ1lnbVFYSmQ4Zkwxang=" -H "Content-Type: application/x-www-form-urlencoded" -d "client_order_id=testv3patchasti21&symbol=XRPUSDT&side=sell&type=stopLimit&time_in_force=GTC&quantity=0.1&price=1.500000&stop_price=1.000000"

RESULT as stopLimit

{
  "id": 704978960525,
  "client_order_id": "testv3patchasti21",
  "symbol": "XRPUSDT",
  "side": "sell",
  "status": "suspended",
  "type": "stopLimit",
  "time_in_force": "GTC",
  "quantity": "0.1",
  "quantity_cumulative": "0",
  "price": "1.500000",
  "stop_price": "1.000000",
  "post_only": false,
  "created_at": "2021-11-10T22:50:00.567Z",
  "updated_at": "2021-11-10T22:50:00.567Z"
}



NOW PATCH


curl -X PATCH "https://api.hitbtc.com/api/3/spot/order/testv3patchasti21" -H "accept: application/json" -H "Authorization: Basic Z2c3X0lhQ08tZTRfSzJBcjR1M0FQd2pUaVQwMXFRSlY6SFJpd0x2S0s3Yk4yYVdfcWVJQ1lnbVFYSmQ4Zkwxang=" -H "Content-Type: application/x-www-form-urlencoded" -d "quantity=0.1&price=1.510000&new_client_order_id=testv3patchasti21yes"




{
  "error": {
    "code": 500,
    "message": "Internal Server Error"
  }
}



what im doing wrong?????
