### ISSUE TITLE
Commodity Withdrawal Fees via API

### ISSUE THREAD

**Issue by moeadham** [hitbtc-com/hitbtc-api#29]
Hello,

To properly price a lot of orders, we need to know the crypto withdrawal fees for each order. Other exchanges return this. Without this information, proper trading/arb strategies are almost impossible on your exchange.

Can you please add this to your 'symbols' endpoint?

Ex:
```javascript
{ symbol: '1STBTC',
       step: '0.000001',
       lot: '0.001',
       currency: 'BTC',
       commodity: '1ST',
       takeLiquidityRate: '0.001',
       provideLiquidityRate: '-0.0001',
       commodityWithdrawalFee: '-0.84' <<<--- ADD THIS PLEASE
}
```

**Comment by moeadham** [comment]
@hitbtc-com Any update on this?

**Comment by hitbtc-com** [comment]
will try to provide. but not for symbol. 
It will be added on currency config (/api/2/public/currency/eth)

**Comment by georgewalther** [comment]
Thanks

**Comment by moeadham** [comment]
@hitbtc-com Do you know how long it will take to add the Withdrawal fee?

**Comment by hitbtc-com** [comment]
I think about week

**Comment by mengus** [comment]
Any news on this?

**Comment by moeadham** [comment]
@hitbtc-com Still not seeing this in the api. Can you at least tell us how you calculate it so we can do the same on our side?

**Comment by moeadham** [comment]
@hitbtc-com Is this on the roadmap at all?

**Comment by nanalyst** [comment]
@moeadham 
i know right? here use this....

```
sh get_hitbtc_fees.sh ~/accounts.html 
hitbtc_withdraw_fees["BTC"] = "-0.0007"
hitbtc_withdraw_fees["ETH"] = "-0.00958"
hitbtc_withdraw_fees["BCH"] = "-0.0018"
hitbtc_withdraw_fees["USD"] = "-5"
hitbtc_withdraw_fees["BTG"] = "-0.0005"
hitbtc_withdraw_fees["XRP"] = "-0.509"
hitbtc_withdraw_fees["DASH"] = "-0.03"
hitbtc_withdraw_fees["LTC"] = "-0.003"
```
this is actually my first github post ever. lol.

the tool is here for you:

```
IyEvYmluL2Jhc2gKIyBEb3dubG9hZCBzb3VyY2Ugb2YgdGhlIGhpdGJ0YyB3YWxsZXQgcGFnZQoj
IFJ1biB0aGlzIHNjcmlwdAojIG5hbmFseXN0IGZpcnN0IGdpdGh1YiBwb3N0IGV2ZXIuIGNtb24g
aGl0YnRjIGxvbCBzb3J0IGl0IG91dC4KaWYgWyAteiAkMSBdCnRoZW4KCWVjaG8gInZpc2l0IGh0
dHBzOi8vaGl0YnRjLmNvbS9hY2NvdW50IHdoaWxlIGxvZ2dlZCBpbiBhbmQgc2F2ZSB0aGUgc291
cmNlIGNvZGUgdG8gYWNjb3VudHMuaHRtbCIKCWVjaG8gIiQwIDxhY2NvdW50cy5odG1sPiIKCWV4
aXQgMQpmaSAKCmNhdCAkMSB8IGdyZXAgImZsYXRfZmVlXy4qIiAtQSA1IDI+JjEgfCBzZWQgLWUg
J3MvIC8gL2cnICB8IGdyZXAgLXYgIl4tLSIgfCBncmVwICItIiB8IGdyZXAgInNwYW4iIHwgc2Vk
IC1lICdzLyAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAvL2cnIHwgc2VkIC1lICdzLyAgLy9nJyB8IHNlZCAtZSAncy88XC9zcGFuPjxc
L2xhYmVsPi8vZycgfCBzZWQgLWUgJ3MvXi0vL2cnIHwgZ3JlcCAtdiAiZXN0aW1hdGUiIHwgYXdr
ICd7cHJpbnQgImhpdGJ0Y193aXRoZHJhd19mZWVzW1wiIiQyIlwiXSA9IFwiLSIkMSJcIiJ9JwoK
```

@hitbtc-com yeah uh, can ya sort it out plz thx cheers love ya work thx m8

**Comment by ibiscp** [comment]
Any news on this?

**Comment by mengus** [comment]
So.. hows it going? Took a look at /api/2/public/currency/eth, and looked thorugh the docs one more time and I still can't find the transfer fee anywhere. Do I really need a crawler for this? 
Or do like moeadham suggests above and tell us how you calculate it, so we can do it on our side.

**Comment by moeadham** [comment]
I don't know what is going on with this one @mengus But I think they have some major bugs here. The current fee to withdraw POE (an ethereum token) is 161$. Something is very wrong here.

**Comment by hitbtc-com** [comment]
added new property "payoutFee"

https://api.hitbtc.com/api/2/public/currency/ETH

{
"id": "ETH",
"fullName": "Ethereum",
"crypto": true,
"payinEnabled": true,
"payinPaymentId": false,
"payinConfirmations": 2,
"payoutEnabled": true,
"payoutIsPaymentId": false,
"transferEnabled": true,
"delisted": false,
"payoutFee": "0.00958"
}

**Comment by parachutingturtle** [comment]
Hi!
I'd like to request that in a similar fashion, the **deposit fee** should also be included in the same result, for currencies that have such a fee.

**Comment by hitbtc-com** [comment]
For now only BTC have deposit commission

**Comment by moeadham** [comment]
Do you mind answering why some of these fees are so high? They are close to 70$ for most tokens.

**Comment by mrHelg** [comment]
What difference between "takeLiquidityRate" and "provideLiquidityRate"?
