### ISSUE TITLE
API docs clarification, some params from mandatory to optional?

### ISSUE THREAD

**Issue by jangorecki** [hitbtc-com/hitbtc-api#3]
1. In the method `trading/new_order` ([link](https://github.com/hitbtc-com/hitbtc-api#neworder)) there is a parameter `clientOrderId` with following description
`Unique order ID generated by client. From 8 to 32 characters`
Can you clarify the uniqueness of it? it has to be unique for:
 - whole client account
 - particular api key set
 - particular symbol (=currency pair) within client account

2. If the answer for question 1. is not **particular symbol** then why do we need `symbol` parameter as mandatory in `trading/cancel_order` ([link](https://github.com/hitbtc-com/hitbtc-api#cancelorder)) method? Could you change it to optional?

3. Still regarding `trading/cancel_order` ([link](https://github.com/hitbtc-com/hitbtc-api#cancelorder)). As we need to cancel order by particular ID is there any reason to have mandatory `side` parameter? Could you change it to optional?

4. Minor, most of parameters description in `trading/cancel_order` ([link](https://github.com/hitbtc-com/hitbtc-api#cancelorder)) mention following phrase `the same as in cancelling order`. I believe it should be `as in opening order` instead of that.

Changing mentioned params (`symbol` and `side` in `trading/cancel_order` method) from mandatory to optional will improve the API interface to be more aligned to already existing biggest exchanges (bitstamp, kraken, btce, ex-mtgox) as none of them requires symbol or side to only cancel the order, they all need only unique id. Of course it is works like this not only biggest exchanges but most of the smaller ones too.

Also such change could be implemented without any trade-off!

**Comment by hitbtc-com** [comment]
Solved
