### ISSUE TITLE
No documentation for v2 streaming API

### ISSUE THREAD

**Issue by freekzero** [hitbtc-com/hitbtc-api#31]
An endpoint is mentioned, but that's it.

**Comment by hitbtc-com** [comment]
We are working on it.

**Comment by freekzero** [comment]
Thanks for the response. Any ETA? I'm chomping at the bit to use this API.

**Comment by Ro0TT** [comment]
UP, need info about Streaming v2.

**Comment by andre77** [comment]
@hitbtc-com  could you clarify a bit please?
is the documentation for v2 streaming api not ready yet, or is the server side implementation not done/finished at all?
thanks

**Comment by aldanor** [comment]
@hitbtc-com Any updates?

**Comment by atouloupis** [comment]
@hitbtc-com No news about it ?

**Comment by georgewalther** [comment]
Thanks

**Comment by hitbtc-com** [comment]
now you can try it:
https://github.com/hitbtc-com/hitbtc-api/blob/master/APIv2.md#socket-api-reference

**Comment by atouloupis** [comment]
Great, everything is working well
