### ISSUE TITLE
Get historical Ticker data

### ISSUE THREAD

**Issue by tomeh100** [hitbtc-com/hitbtc-api#34]
NO API method to Get historical Ticker data

**Comment by hitbtc-com** [comment]
can you provide an example of what you want?

**Comment by tomeh100** [comment]
sure

Retrieve a list historical price data (candlesticks) based time interval, duration and that will return candlestick data like (open, high, low, close and volume) 
/api/symbol/COSSETH/60sec/5days

expected result:
"result":[
  {"open":0.002, "high":0.0021, "low": 0.0019, "close": "0.0021"},
  {"open":0.002, "high":0.0021, "low": 0.0019, "close": "0.0021"},
  {"open":0.002, "high":0.0021, "low": 0.0019, "close": "0.0021"},
]

**Comment by hitbtc-com** [comment]
spec: https://github.com/hitbtc-com/hitbtc-api/blob/master/APIv2.md#candles
socket: https://github.com/hitbtc-com/hitbtc-api/blob/master/APIv2.md#subscribe-to-candles
example: https://api.hitbtc.com/api/2/public/candles/ethbtc?limit=1000&period=M30
