### ISSUE TITLE
Socket API: Subscribe to change my balance / new trades (MY TRADES, not all)

### ISSUE THREAD

**Issue by Wo0nder** [hitbtc-com/hitbtc-api#36]
Why this minimal set of necessary subscribe is not implemented? Instead, we spam you with requests.
Or maybe I do not know something?

Need to impliment 2 important subscribe:
- changes account balance;
- add new trades for my account.

**Comment by Ro0TT** [comment]
Up need **subscribe for changes account balance**, I found trades in the subscribeReport.

**Comment by martonb** [comment]
I agree, it is spammy to keep re-requesting the full list!

**Comment by Gkathuria2** [comment]
My XEM withdrawal is pending from last 60 hours

Operational id is a58bd9db-2f8f-44f7-b585-dd94913b6712

kindly check these tickets #251471
#251092

Now XEM is offline on receiving address, please cancel withdrawal request and add fund back.

@HitBTC_Support_Team

**Comment by hitbtc-com** [comment]
hi @Wo0nder 
You can subscribe to report updates. Changes account balance is on the way
