### ISSUE TITLE
Sockets APIv2: there is no unification in subscribeOrderBook messages

### ISSUE THREAD

**Issue by Ro0TT** [hitbtc-com/hitbtc-api#37]
In **snapshotOrderbook** we have not param 'data' in `params {}`
```
params.ask
params.bid
```

In **updateOrderbook** we have param 'data' in `params {}`
```
params.data.ask
params.data.bid
```

What for? In fact, this is the same information, but in different volumes. Can you unify it? Thx.

**Comment by hitbtc-com** [comment]
fixed!

**Comment by asavis** [comment]
Please notify you users before doing API changes.
