### ISSUE TITLE
No connection endpoints for FIX api are given

### ISSUE THREAD

**Issue by sdrobs** [hitbtc-com/hitbtc-api#39]
I've looked through all the docs provided for the FIX api, and can't find a host or endpoint provided to connect to. The only thing the docs say is that you can connect with openvpn and that there is a different endpoint for market data and trading. This is insufficient information for getting connected.

I thought maybe I needed to file a support ticket to get access, but it has been 6 weeks and I haven't received any reply. How is anybody even using the FIX api if the connection endpoints / related info doesn't seem to exist?

**Comment by hitbtc-com** [comment]
FIX available after verification and support request
