### ISSUE TITLE
Need proper "orderinfo" call

### ISSUE THREAD

**Issue by Serpens66** [hitbtc-com/hitbtc-api#41]
I fear it might be already too late, since you released v2 officially, but maybe there is still a solution:

**Problem:**
When I place an order, directly after it I need information what happend to that order. Was it successfully placed? Was it filled or still unfilled? Was it cancelled for whatever reason (some exchanges do it, eg to prevent self trading or when they disabled trading)? Or it even can be "submitted" at other exchanges, cause of too slow trading engine, not sure if such does exist at hitbtc.

You have an "active order" check, but if the order was filled/cancelled, it will not help.
And the order/history is only updated every ~30 seconds.

**Question/Possible Solution:**
So what are my options while not using websocket?
Currently, if the order is not in active orders, I assueme that it was successfully filled, which is right most of the times.

But I also receive alot of "timeouts" (more than 10 seconds no response) in high traffic times, when trying to cancel an order. If this happens I need to check if the order was filled or cancelled. But this is not possible, at least not without waiting 30 seconds, to let the order/history update.

So I would like to see some kind of call, that will return the actual status of my order without any delay, regardless of the status. I need to know if it was cancelled or filled immediately.

**Comment by hitbtc-com** [comment]
Only one right way - use WebSocket API. You will receive all order updates. Socket API protocol is really easy and effort for your purposes.
Rest API useful is only for easy scenarios
