### ISSUE TITLE
Follow up on Ticket no. 49515, Withdrawal not processed-Day 3

### ISSUE THREAD

**Issue by naaybalodia** [hitbtc-com/hitbtc-api#42]
Details of the withdrawal initiated

Address: 0x071dd94faae2151237a78c86048722129502c118
Transaction hash: 0xa8bdabed750257f0baa5fe525837ec6af4d4abafbe06167de1e5439b01f5db2d
Operation ID: 54625b4d-09d1-4349-b605-671497a6a0be
Date Created (UTC): 19/11/2017, 09:28:21
Date Updated (UTC): 19/11/2017, 09:56:14
Thanks
It's over 2 days and still not processed. The transaction hash is not there in the blockchain either. Please help me, team. Till now it has been a pleasant experience. Only withdrawal seems a bit slow. 

I want to continue trying in hitbtc.

I will give strong positive reviews to hitbtc on quick assistance from the team. 

Help would really be appreciated! :)

**Comment by hitbtc-com** [comment]
Solved
