### ISSUE TITLE
Timestamp filter does not work - Candles resource 

### ISSUE THREAD

**Issue by guilhermeagirardi** [hitbtc-com/hitbtc-api#44]
Hello!

I need the history of candlesticks since the beginning of the year. However when informing the initial timestamp and final timestamp nothing happens.

So I went to plan B, increase the limit of results, but it only allows up to 1000.

Do you have any other possibility of doing this consultation? Something is wrong, we are tied to older information.

Best regards

**Comment by hitbtc-com** [comment]
Full candlesticks data is not provided
