### ISSUE TITLE
Got not actual data from order book get request if send it from RU IP

### ISSUE THREAD

**Issue by akravchenko1986** [hitbtc-com/hitbtc-api#45]
Hello, devs.
I've got a very strange but annoying issue.
I'm trying to get current book to some instrument (ETHUSD for example) via get request here:
https://api.hitbtc.com/api/2/public/orderbook/ETHUSD?limit=1
and I'm always getting the same and  not actual market data: 
{"ask":[{"price":"464.67","size":"0.254"}],"bid":[{"price":"462.70","size":"17.365"}]}

But if I'm sending the same request from some European IP (Netherlands for example)/, I'm getting the actual book:
{"ask":[{"price":"463.89","size":"0.168"}],"bid":[{"price":"462.58","size":"0.120"}]}

Could you, please, explain if it is a bug or a "feature"? :)

Thanks.

P.S.: Didn't find any strange responds on other requests from RU IP so far.

**Comment by akravchenko1986** [comment]
Forgot to add some crucial info:
RU IP: 46.188.122.49 - issue reproduces
GB IP: 128.199.238.125 - issues not reproduces

**Comment by huangjosh** [comment]
@akravchenko1986 Do you fix this issue? I face the same issue. This also happens in my server in other region with other symbol. 
@hitbtc-com I think you may cache the orderbook result in the server, but the cache is outdated for some servers, which cause the orderbook result outdated?

**Comment by hitbtc-com** [comment]
Thank you very much for your information. Fixed.
