### ISSUE TITLE
API v2, the subscription method for updating orders has ceased to work.

### ISSUE THREAD

**Issue by Ro0TT** [hitbtc-com/hitbtc-api#46]
After send message '{"method": "subscribeOrderbook","params": {"symbol":"ETHBTC"},"id": 123}'. I get a snapshot, but no longer comes with an indistinct message.

Broke, today. Need HOT FIX.

![image](https://user-images.githubusercontent.com/2150895/33344688-e5a40ee6-d49a-11e7-92ea-d042370a6074.png)

**Comment by freekzero** [comment]
This is doubly critical since the v1 API has been down for a couple days. I did the work to update to v2 only to find it is now also unusable.

**Comment by hitbtc-com** [comment]
Test it please again

**Comment by Ro0TT** [comment]
It's work! Thx.
