### ISSUE TITLE
Missing NXT - filed support ticket, no response.

### ISSUE THREAD

**Issue by ADA4life** [hitbtc-com/hitbtc-api#48]
Hi HitBTC,

I have already filed this case number quite some time ago, Case #57704 but I am not receiving a response.

I sent 393 (390 NXT after fee) to my Bittrex NXT wallet. On HitBTC, I do not see an option to include a note, which Bittrex has required for the deposit to funds correctly they state. 

Can you please help me recover these funds?

Transaction hash 17309953900365968557

**Comment by Graal46** [comment]
s

**Comment by Gkathuria2** [comment]
My XEM withdrawal is pending from last 60 hours

Operational id is a58bd9db-2f8f-44f7-b585-dd94913b6712

kindly check these tickets #251471
#251092

Now XEM is offline on receiving address, please cancel withdrawal request and add fund back.

@HitBTC_Support_Team

**Comment by hitbtc-com** [comment]
Dear @ADA4life, I believe your issue was resolved, as well as yours, @Gkathuria2 - enjoy trading with HitBTC!
