### ISSUE TITLE
Withdrawal..

### ISSUE THREAD

**Issue by Holderxx** [hitbtc-com/hitbtc-api#49]
HitBTCSupportTeam
BTG withdrawal 74.509 amount..
Ticket ID: 58921
Process ID:46d9a846-c99a-4062-95a7-0e19eab37c0b
I wait 8 days!!!  Please help me...

**Comment by Graal46** [comment]
,

**Comment by Gkathuria2** [comment]
My XEM withdrawal is pending from last 60 hours

Operational id is a58bd9db-2f8f-44f7-b585-dd94913b6712

kindly check these tickets #251471
#251092

Now XEM is offline on receiving address, please cancel withdrawal request and add fund back.

@HitBTC_Support_Team

**Comment by hitbtc-com** [comment]
Dear @Holderxx, was your issue resolved? Please, let us know.
Please, do not comment in multiple threads regarding the same issue, @Gkathuria2.
