### ISSUE TITLE
Affiliate Panel 

### ISSUE THREAD

**Issue by macd2** [hitbtc-com/hitbtc-api#50]
Hello,
affiliate states are not updated since 8 Days, come on please fix!

**Comment by Gkathuria2** [comment]
My XEM withdrawal is pending from last 60 hours

Operational id is a58bd9db-2f8f-44f7-b585-dd94913b6712

kindly check these tickets #251471
#251092

Now XEM is offline on receiving address, please cancel withdrawal request and add fund back.

@HitBTC_Support_Team
