### ISSUE TITLE
ETH disappeared from the transaction account to the main account.

### ISSUE THREAD

**Issue by sdzb111** [hitbtc-com/hitbtc-api#51]
[1).xlsx](https://github.com/hitbtc-com/hitbtc-api/files/1544733/1.xlsx)
In November 23rd, when I operated my HIT account and removed the ETH from the transaction account to the main account, ETH disappeared. Under the negotiation with HIT many times, HIT was caused by technical problems, and has not yet been processed. The record from the transaction account to the main account is displayed, but then the ETH is not. Please solve the problem. Is it a BUG of HIT?
![1](https://user-images.githubusercontent.com/34376669/33796519-d09f251e-dd30-11e7-8d96-b579f0f4abcb.jpg)

**Comment by sdzb111** [comment]
11月23日，我操作我的HIT账号，把ETH从交易账号到主账号后，ETH就消失了，在和HIT的多次交涉下，HIT说是技术问题导致的，至今也未能处理。在从交易账号到主账号的记录有显示，但之后ETH就没有了。请技术高手帮给解决下吧。是不是HIT的一个BUG

**Comment by Graal46** [comment]
Issue moved to [hitbtc-com/hitbtc-php-sdk #10](https://github.com/hitbtc-com/hitbtc-php-sdk/issues/10) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Gkathuria2** [comment]
My XEM withdrawal is pending from last 60 hours

Operational id is a58bd9db-2f8f-44f7-b585-dd94913b6712

kindly check these tickets #251471
#251092

Now XEM is offline on receiving address, please cancel withdrawal request and add fund back.

@HitBTC_Support_Team

**Comment by hitbtc-com** [comment]
Dear @sdzb111, can you please state if the issue is still relevant? Thanks in advance!
