### ISSUE TITLE
Withdraw Fail

### ISSUE THREAD

**Issue by chillyeyes** [hitbtc-com/hitbtc-api#52]
This is my first time to stuck in a bad situation. 
I think that HITBTC has the ability to get over it. Please help to complete my withdraw. Thanks a lot~

Address: 0xCF74c0d56601b9812A452d8Af4408E77F000b0A7
Transaction hash: 0x12f8e5ffeb4d80e6bbef0caa34870b94164a960326f13cb2d807f85e801baab0
Operation ID: 4ec9a9e8-bc8d-490c-818c-17034dc0be41
Date Created (+08): 20/12/2017, 11:13:08

Address: 0xCF74c0d56601b9812A452d8Af4408E77F000b0A7
Transaction hash: 0x3eb2bcccbf845ff33724684c4c501373e0ef7ff3812dbcdc929bb3e0fc9169d7
ID: 2142baed-76d7-4c09-a7b0-5b6553956823 
Date Created (+08): 2017-12-08, 00:46:10

Address: 0xCF74c0d56601b9812A452d8Af4408E77F000b0A7
Transaction hash: 0x8ed7081a9d7098ee309ace30521b29de2cb5181b5c15d16a970cef1334de4168	
ID: 9187e524-7d7e-466f-ae4d-7ffd24acf895
Date Created (+08): 2017-12-06, 22:42:31

**Comment by baij-patel** [comment]
I think they are a scam site. I have been trying to withdraw for days now.

**Comment by Gkathuria2** [comment]
My XEM withdrawal is pending from last 60 hours

Operational id is a58bd9db-2f8f-44f7-b585-dd94913b6712

kindly check these tickets #251471
#251092

Now XEM is offline on receiving address, please cancel withdrawal request and add fund back.

@HitBTC_Support_Team
