### ISSUE TITLE
API stopped working on Friday morning

### ISSUE THREAD

**Issue by franceq** [hitbtc-com/hitbtc-api#54]
Hi,
I have traded on hitbtc for lot of months using the API. Everything worked well since this Friday morning when i found out, that I was banned from API, the service stopped working and also I can not even display the API documentation on the web. It is same for all my public IPs. I am definitely not a spammer, I regulate the number of request on as low number as possible, I also used web socket to do as much as possible asynchronously. I absolutely do not understand  the situation. I have paid each month thousands of US dollars in fees and also I did nothing harmful. I am just a trader. I have changed my public IP with my internet provider, but it did not help, so I even tried to change MAC address of the network device with the public IP and it did not help also. It seems that they blocked all IP range I have used (it can be thousands of IPs). Unfortunately hitbtc support absolutely ignores my tickets and nobody is responding to my cry. Is there anybody who has same experience?

**Comment by incazteca** [comment]
I got the same issue, and I just started using the API today. This is for the REST API v2

```
(.env) franco@BB-8:~/development_zone/trader_prototype (master)$ python historic_prices.py
Traceback (most recent call last):
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.hitbtc.com', port=443): Max retries exceeded with url: /api/2/public/candles/DOGE?limit=100&period=M1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc4ca0d8c50>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable',))
(.env) franco@BB-8:~/development_zone/trader_prototype (master)$
```

I'm immediately getting a max retries attempted error

**Comment by franceq** [comment]
I created few days ago new topic on HitBTC forum and their support team responded today (18. 12. 2017) morning. They know about it and according them their engineers are working on it.
[Link to the topic](https://forum.hitbtc.com/discussion/2627/api-doesn-t-working#latest)

**Comment by hitbtc-com** [comment]
it was a temporary problem, related to DDOS
