### ISSUE TITLE
Feature request: identifying deposits

### ISSUE THREAD

**Issue by pauliusuza** [hitbtc-com/hitbtc-api#56]
Hello,

There is currently no way to identify deposits through API v2. 

1. Would it be possible to include a "payinAddress" field in the /account/transactions and /account/transactions/{id} responses of type "payin", which will show the address into which the payin was received at the time?

2. Would it be possible to send an additional string "id" parameter when requesting a new deposit address? If hitbtc has already created and associated a deposit address with "id" parameter, it would return that address. Otherwise it would create a new address and associate it with the provided "id" parameter.

Thanks

**Comment by pauliusuza** [comment]
And 3 follow up questions:

1. if I create 3 deposit addresses through API, only the last one will be visible through the UI, but will all 3 addresses will be attached to my account or they get discarded / disabled when a new address is created?
2. Are there limits to number of deposit address I can add to an account?
3. Do deposit addresses get re-used on other accounts?

**Comment by hitbtc-com** [comment]
All address created for your account available for deposit and never re-used. But we recommend use the last address and always get it via API (not save or cache)

5 address per 24 hours you can create deposit address.

"payinAddress" currently not available, but you have "hash"
