### ISSUE TITLE
Orders DELETE by symbol NOT WORK

### ISSUE THREAD

**Issue by Ro0TT** [hitbtc-com/hitbtc-api#57]
**[DELETE] https://api.hitbtc.com/api/2/order?symbol=XUCUSD:**
`[{"id":"10312610474","clientOrderId":"d43f4dd8-e696-45d8-a734-310782","symbol":"EDOUSD","side":"buy","status":"canceled","type":"limit","timeInForce":"GTC","quantity":"10.00","price":"3.06","cumQuantity":"0.00","createdAt":"2017-12-18T19:56:07.345Z","updatedAt":"2017-12-18T20:00:21.522Z"},{"id":"10312661355","clientOrderId":"fdd5d712c5a62621eea8066d1dcbc812","symbol":"WRCUSD","side":"buy","status":"canceled","type":"limit","timeInForce":"GTC","quantity":"100","price":"0.0822","cumQuantity":"0","createdAt":"2017-12-18T19:56:52.471Z","updatedAt":"2017-12-18T20:00:21.522Z"},{"id":"10312763773","clientOrderId":"866a049f-2dce-4622-adba-ebc7a0","symbol":"ATBUSD","side":"buy","status":"canceled","type":"limit","timeInForce":"GTC","quantity":"10.0","price":"0.539","cumQuantity":"0.0","createdAt":"2017-12-18T19:58:27.794Z","updatedAt":"2017-12-18T20:00:21.522Z"}]`

How it work, why delete all orders on account?

**Comment by Ro0TT** [comment]
actual

**Comment by hitbtc-com** [comment]
send symbol=XUCUSD into payload, not as query parameter
