### ISSUE TITLE
Withdrawal frozen in pending for 10 days.

### ISSUE THREAD

**Issue by rayovax** [hitbtc-com/hitbtc-api#58]
ID 49c8cd5b-c3ec-4619-8ae5-ef6f68054f13

**Comment by baij-patel** [comment]
I think they are a scam site. I have been trying to withdraw for days now.

**Comment by aaahmadi** [comment]
rayovax im payed u tell me what is ur problem i pay u mate

**Comment by Gkathuria2** [comment]
My XEM withdrawal is pending from last 60 hours

Operational id is a58bd9db-2f8f-44f7-b585-dd94913b6712

kindly check these tickets #251471
#251092

Now XEM is offline on receiving address, please cancel withdrawal request and add fund back.

@HitBTC_Support_Team

**Comment by hitbtc-com** [comment]
Dear @rayovax, @baij-patel and @aaahmadi  - can you state if your issues are still relevant?
Please provide us with ticket numbers if they are. Thanks!
