### ISSUE TITLE
WebSocket API: trades that don't match any price points in the book

### ISSUE THREAD

**Issue by infra-diatonic-scale** [hitbtc-com/hitbtc-api#59]
This seems to happen very often, with fair regularity:

1) Connect to WebSocket API, receive a snapshot; let's say best bid is now 100 and best ask is 101
2) Receive a few dozen book updates
3) Then a trade message comes in, with a trade price of 100.5

This price point (100.5) is nowhere to be seen neither in the snapshot, nor in the previous book updates, or the updates to follow. Is there an explanation for this? How should this be handled?

(For most other trades, normally, if you subscribed to both the orderbook and trades channels, you first receive a book update matching the trade, potentially spanning multiple book levels, and the following packet will contain the trade messages)

Would appreciate any clarification on this, thanks.

**Comment by alexanderborsch** [comment]
They will match if they are your trades, looks like a scam

**Comment by hitbtc-com** [comment]
book update is diff of aggregated orders updates during 100 ms. 
if someone place buy order with price for example 100.5 and someone else sell order with the same price and quantity, then no orderbook changes, but trade occurred

**Comment by lvhf1971** [comment]
我要退订这个邮件，不知道怎样退订这个邮件，请给予帮忙




发自网易邮箱大师
On 2/8/2018 18:26，hitbtc-com<notifications@github.com> wrote：

Closed #59.
