### ISSUE TITLE
How get fee for transaction?

### ISSUE THREAD

**Issue by izoomrud** [hitbtc-com/hitbtc-api#60]
Hi, how get fee for transaction like poloniex txFee - https://poloniex.com/public?command=returnCurrencies

**Comment by hitbtc-com** [comment]
added new property "payoutFee"

https://api.hitbtc.com/api/2/public/currency/ETH
{
"id": "ETH",
"fullName": "Ethereum",
"crypto": true,
"payinEnabled": true,
"payinPaymentId": false,
"payinConfirmations": 2,
"payoutEnabled": true,
"payoutIsPaymentId": false,
"transferEnabled": true,
"delisted": false,
"payoutFee": "0.00958"
}
