### ISSUE TITLE
OLD BTC Address In BTC Deposited amount, New BTC Address 0 reflect

### ISSUE THREAD

**Issue by yameyamo** [hitbtc-com/hitbtc-api#61]
Hi hitbtc support . Please go thru my Ticket ID #83137.

It's been Quite sometimes that I've deposit btc into hitbtc . Blockchain shown the amount was unspent output and successfully transfered. But in my hitbtc btc wallet still shown 0. What is going on? 

As I said it's been quite sometimes, when I still using the OLD BTC address,
But recently i regenerate New address, but it still doesn't reflect. Please help.

**Comment by Graal46** [comment]
?!

**Comment by Graal46** [comment]
36xpJskhMxQXME2aAr5VuxdTxJVMPedsmH

**Comment by aaahmadi** [comment]
give me ur wallet
