### ISSUE TITLE
Suggestion: Balance updates

### ISSUE THREAD

**Issue by Serpens66** [hitbtc-com/hitbtc-api#62]
You could add a "subscribe to balance" for authenticated users. 
Everytime the available/total balance changes, the user could receive an update with the new balance.

In case you do not want to offer it, make it possible to calculate the balance on our own. In case calculating is already possible, please write a short guide which notifications we should use in what way to calculate.

**Comment by martonb** [comment]
Indeed, currently there is no way to request for instance just the trading balances that have non zero values neither, so every time I request it, I have to process a long list.

So, give us notifications about the trading balance, or at least make it a param of the request to get the full list or only the non zero items of the list.

**Comment by martonb** [comment]
@Serpens66 yes, I am using the request via WebSocket, but it gives back a huge reply, which has to be processed, using up CPU. Also, I have to re-request that periodically, to be up to date.
