### ISSUE TITLE
USDT total balance with webSockets API

### ISSUE THREAD

**Issue by Macarthurval** [hitbtc-com/hitbtc-api#63]
Hello, I would like to get the current USDT balance via websocket API, can you tell me if there is a method for that?, I can't find it.

This is what I'm talking about, the USDT field:

<img width="241" alt="captura de pantalla 2017-12-23 a la s 14 05 28" src="https://user-images.githubusercontent.com/30457050/34322019-628691a6-e7ea-11e7-9d93-0c7af1f2d162.png">

Thanks in advance.

**Comment by Serpens66** [comment]
https://github.com/hitbtc-com/hitbtc-api#get-trading-balance
