### ISSUE TITLE
Deposit CENTRA TOKEN issue.. more 3 days is still pending

### ISSUE THREAD

**Issue by rainbowRNB** [hitbtc-com/hitbtc-api#66]
I try to send my centra token from MEW to my hitbtc account,but until today my balance is still zero... this is my tx hash... please fix it as soon as possible...

https://etherscan.io/tx/0xc0be793a2af5eebc2d1879662bb28786664b433c14f223f8e361009ddc783a88

**Comment by hitbtc-com** [comment]
Send it to support pliz
