### ISSUE TITLE
Tron deposits unavailable

### ISSUE THREAD

**Issue by punnymarty** [hitbtc-com/hitbtc-api#68]
Many users have been facing issue since last many days of unable of getting deposits in their tron wallets even though the transaction on blockchain is successful. This has led to many people not being able to trade and hence losing time and thus money.

Your team has acknowledged the issues, but please give us an ETA as well, so we know if it is gonna come or we're actually being scammed!

**Comment by baij-patel** [comment]
I think they are a scam site. I have been trying to withdraw for days now.

**Comment by hitbtc-com** [comment]
TRON delisted
