### ISSUE TITLE
Follow up on ticket #137230, withdrawal not processed Day 4

### ISSUE THREAD

**Issue by omufleh** [hitbtc-com/hitbtc-api#70]
Im still waiting for my withdraw to take place (BTC and XVG) , its has been more than 11 hours; would appreciate it if you could proceed with my transactions the soonest. 

Date: 2018-01-04, 09:17:20
ID: bc71f693-01ff-4335-8f71-767577541c0b
Transaction Hash: 560b58a33f380b87940917790f046026d269202c8636c9bf842e6af80064a828
Withdraw	BTC 0.20629521

Date: 2018-01-04, 08:56:00
ID: 9f84378c-abf3-4d9b-920a-aa6ee6593075
No Transaction Hash
Withdraw	XVG	998.50000000

Help would really be appreciated,

Thank you,

**Comment by omufleh** [comment]
Day 3 and still in process

**Comment by baij-patel** [comment]
I think they are a scam site. I have been trying to withdraw for days now.

**Comment by hitbtc-com** [comment]
Dear @omufleh, I believe your issue was resolved already - can you please state if the issue's still relevant? Thanks!
