### ISSUE TITLE
!Withdrawal won't proceed more than 30 hours in BTC!

### ISSUE THREAD

**Issue by hardmentimur** [hitbtc-com/hitbtc-api#72]
Hello.
03/01/2018 I withdeawal from my accoun a lot of BTC
At the moment more than 30 hours have passed. The conclusion is not perfect. There is not even a hash transaction. What is the problem? Answer me on the message!
Operation ID: 3a06eb23-aaa2-41fd-b845-cd68e7620ed8
Date Created (UTC): 03/01/2018, 12:01:26
Date Updated (UTC): 03/01/2018, 12:01:26
hardmentimur@gmail.com

**Comment by ourway** [comment]
Is this resolved?

**Comment by hardmentimur** [comment]
No

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-06 0:43 GMT+02:00 Farsheed Ashouri <notifications@github.com>:

**Comment by hitbtc-com** [comment]
Send it to support pliz
