### ISSUE TITLE
BQX withdrawal also waiting 3 days, fake hash given not on blockchain

### ISSUE THREAD

**Issue by calvinsmedia** [hitbtc-com/hitbtc-api#73]
no support given and fake hash given
have been waiting far too long, have also put in a few tickets to sort this, only a small amount but a lot to me

Address: 0xb5b97930e6a8d25++++++++++++++++++
Transaction hash: 0x70afec8b410c72b4efec7e3086f6++++++++++++++++++++++++
Operation ID: 8dade2d0-eb38-4f87-b7f9-2914c4eee31f
Date Created (UTC): 03/01/2018, 20:28:29
Date Updated (UTC): 03/01/2018, 20:28:29

**Comment by ourway** [comment]
Is it resolved?

**Comment by SallyDT** [comment]
I have similar issue. Not resolved...

Fake hash given...

**Comment by ourway** [comment]
Interesting that they are not answering!

**Comment by hitbtc-com** [comment]
Send it to support pliz
