### ISSUE TITLE
deposit (SC) since 8 days

### ISSUE THREAD

**Issue by osama24111990** [hitbtc-com/hitbtc-api#75]
Ticket-ID is #151627 Address: 828a26766b5065d66a8cefa45184163cebc4c9d4fe6b9374dbc6381488aa4f2b604143aebd5b 
TxId: a9550f4ec833449f5b119220ad855c6264609b61d6f4de4086c6b1d7c4695e8 
Coin name: SC - SiaCoin 
number of units: 435500.54388009 
Deposit date: 12/30/2017 
the problem: I have not received a deposit since 8 days

I hope you will pass the deposit to my account now without delay

**Comment by hitbtc-com** [comment]
Send it to support pliz
