### ISSUE TITLE
The withdrawal request is over 50 hours

### ISSUE THREAD

**Issue by leechangmin1** [hitbtc-com/hitbtc-api#76]
The withdrawal request is over 50 hours

What the hell are you doing?
Solve withdrawal problems

Address: 0x93750d7861d1111343c78a36caa771b785b92e60

Transaction hash: 0x2eafa57d2eb65063cc3badf1639af0ae9018583d03cf3c0d0bb9c0e2229313ba
(It may be changed before the transaction is confirmed)

Operation ID: 74308fcf-bfe8-49c6-bf7c-0e8b2d934918
Date Created (UTC): 05/01/2018, 11:42:55
Date Updated (UTC): 05/01/2018, 11:42:55

**Comment by baij-patel** [comment]
I think they are a scam site.  I have been trying to withdraw for several days now.
