### ISSUE TITLE
The withdrawal request is over 3 days. Help me, please!!!

### ISSUE THREAD

**Issue by d3d8** [hitbtc-com/hitbtc-api#77]
Solve withdrawal problems! Help me please
Address: 12XCH9p9myVe6AbawWYdt4Bf3FtG5qGFBd
Transaction hash: 283dc05f73e460502bf6043eb68f4b0c5cd88635ec78be8112cf7c766e3058c0
Operation ID: 3353748f-03e5-4f39-bae4-4677080aa168
Date Created (UTC): 04/01/2018, 21:32:34
Date Updated (UTC): 04/01/2018, 21:32:34

++++++

Address: 1oZ9Ku2evL4uLCttyrXktB14YMmdkKqNd
Operation ID: 16f51990-a855-413a-8a65-ce018f68abc6
Date Created (UTC): 05/01/2018, 11:38:58
Date Updated (UTC): 05/01/2018, 11:38:58

**Comment by d3d8** [comment]
btc - ok! USDT NO!!!!

**Comment by hitbtc-com** [comment]
Send it to support pliz
