### ISSUE TITLE
The withdrawal request is over 3 days. 

### ISSUE THREAD

**Issue by jaycrypto2001** [hitbtc-com/hitbtc-api#78]
Id #16025

I haven't got my ETH yet.

**Comment by aaahmadi** [comment]
i dont undrestand you
 whats your mean!

**Comment by aaahmadi** [comment]
give me ur etherium wallet

**Comment by jaycrypto2001** [comment]
hitbtc
 
 	Dear Customer,
You requested to withdraw 6.41446000 ETH to address 0x7695eee8f10219517609511e32bbc699fb678ca0.
Please confirm this action by clicking on this link:
https://hitbtc.com/billing/verify-withdraw/fab1e958624cb3493626e872f6c06297

Your request for this action will expire in 1 hour.



Best regards,
HitBTC Team

**Comment by jaycrypto2001** [comment]
I gave you my wallet and nothing hasn’t arrived yet.

**Comment by baij-patel** [comment]
Same issue here - cannot withdraw any currencies/coins at all.  Have been trying for days.  I think that we are all victims of a big scam and will be losing our money...

**Comment by jaycrypto2001** [comment]
I’m going to hunt them down!
I’ll find out everything about each one is involved, then I’ll publish everything about their parents, kids, spouse and especially their past. They are fucked with me! 

Everything is Crypto

**Comment by aaahmadi** [comment]
whats ur problem jaycrypto?

**Comment by jaycrypto2001** [comment]
They have my 6 ETH still.

You requested to withdraw 6.41446000 ETH to address 0x7695eee8f10219517609511e32bbc699fb678ca0.
Please confirm this action by clicking on this link:
https://hitbtc.com/billing/verify-withdraw/fab1e958624cb3493626e872f6c06297

Your request for this action will expire in 1 hour.

Best regards,
HitBTC Team

Everything is Crypto

**Comment by aaahmadi** [comment]
Unfortunately I can not access my account

**Comment by ussingh** [comment]
Please solve ticket  ID #186156
My eth withdrawal still pending since 2 days ago, How long it takes time

**Comment by Gkathuria2** [comment]
My XEM withdrawal is pending from last 60 hours

Operational id is a58bd9db-2f8f-44f7-b585-dd94913b6712

kindly check these tickets #251471
#251092

Now XEM is offline on receiving address, please cancel withdrawal request and add fund back.

@HitBTC_Support_Team
