### ISSUE TITLE
hitbit !! Is not it really a thief? 

### ISSUE THREAD

**Issue by leechangmin1** [hitbtc-com/hitbtc-api#79]
hitbit !! Is not it really a thief? 
What do you really want? Only deposits and does not withdraw money And are not you going to run away? It's been four days now
. What do you think about the move? 
Can you think it's normal? If you guys are not a scam,
Give me a withdrawal
Address: 0x93750d7861d1111343c78a36caa771b785b92e60 Transaction hash:
0x2eafa57d2eb65063cc3badf1639af0ae9018583d03cf3c0d0bb9c0e2229313ba (It may be changed before the transaction is confirmed)
Operation 
ID: 74308fcf-bfe8-49c6-bf7c-0e8b2d934918 
Date Created (UTC): 05/01/2018, 
11:42:55 Date Updated (UTC): 05/01/2018, 11:42:55

**Comment by aaahmadi** [comment]
0x2cbc33dFA7B07c1aDfdbE9A4c7a30bDDE5f2014E

**Comment by baij-patel** [comment]
I believe they are a scam site and will accept all deposits but not allow withdrawals.

**Comment by aaahmadi** [comment]
Those who work here
They do not want your coins
Do not doubt ... I'm, for example, ten days old
My account is locked due to my mistake
Not open yet, but do not shrink the people
I am a simple user
But christmas is glad
Prove that you think it's a mistake
I send
Merry Christmas

**Comment by aaahmadi** [comment]
👍 unicorn

**Comment by Gkathuria2** [comment]
My XEM withdrawal is pending from last 60 hours

Operational id is a58bd9db-2f8f-44f7-b585-dd94913b6712

kindly check these tickets #251471
#251092

Now XEM is offline on receiving address, please cancel withdrawal request and add fund back.

@HitBTC_Support_Team

**Comment by hitbtc-com** [comment]
Dear @leechangmin1, can you please state if your issue's still relevant? Thanks!
