### ISSUE TITLE
Major Issue/Bug with Multiple XRP Deposits to same Destination Tag

### ISSUE THREAD

**Issue by tlux9** [hitbtc-com/hitbtc-api#80]
Still waiting.... why wont you guys respond to the horrible support issues? At least make an announcement that you are actively investing in support infrastructure and people.... at this point you look like crooks.

On January 7th I wanted to make a 440XRP deposit. I did a small 40XRP deposit for to make sure everything was working. That transfer went through quickly. I then sent the remaining 400XRP to the same destination tag, because the page never refreshed or noted that the destination tag changes each transaction. I am now missing 400XRP, please help.

Support Ticket ID #162909

The original 40XRP test deposit was XRP transaction hash: 82AF502F353849D8811B44C5CD78188C66F0E60977E89E869092995EEA4BA73B
The second transaction for 400XRP was transaction hash: 82AF502F353849D8811B44C5CD78188C66F0E60977E89E869092995EEA4BA73B

Please let me know you guys are working on this and what kind of time frame I need to expect to get this resolved.

**Comment by tlux9** [comment]
No response from anyone at hitBTC in 4 days...

**Comment by aaahmadi** [comment]
u need how many xrp mate?

**Comment by tlux9** [comment]
Missing 400xrp that was deposited to hitBTC

**Comment by aaahmadi** [comment]
I HAVE PROBLEM WITH MY HITBTC ACCONT ( LOST 2FA )  AND HAVE 10000BMC 
22400000 LIFE 👯‍♂️ BUT IM TRY TO BACKED UP WITH CODDING

**Comment by hitbtc-com** [comment]
Dear @tlux9, I believe your issue was already resolved. We appreciate your choice to trade with HitBTC!
