### ISSUE TITLE
Missing VIBE Deposit From 6 Days

### ISSUE THREAD

**Issue by moneykicks007** [hitbtc-com/hitbtc-api#81]
This Is My TrxID https://etherscan.io/tx/0x640bfc3dc217004dfb069c1a4ef14a121d9076274a25b92bfedf1761293c8ef4

Please Help Me With This! It's Too Much Time. You Guys Can't Say That It's Because Of Ethereum Network Is Full. If You Guys Having Problems Then Just Temp. Shut Down Certain Coins Wallets So At Least People Don't Get Stuck And Call You Scam.

**Comment by hitbtc-com** [comment]
Send it to support pliz.
