### ISSUE TITLE
vibe withdrawal

### ISSUE THREAD

**Issue by kuakk** [hitbtc-com/hitbtc-api#82]
ı see this notice on hitbtc

Monitoring subsystem notice

Our monitoring systems show that VIBE daemons are not stable now. Either VIBE network is highly loaded or our servers are overloaded. We are handling it right now and your coins are safe. However, proceeding with withdrawal right now could lead to your transaction being delayed or stuck, until we manually process it, which in the worst case can take up to 4 weeks. 
We apologise for any inconvenience caused.

but I did not have any warnings during withdrawal today.

please either cancel or send the transaction

Address: 0xbd23b5128da766bc36f93987fc1059dc29b6a8e5
Operation ID: 44e70eb2-4681-428e-9a1f-62a56382fd7b
Date Created (+03): 10/01/2018, 15:51:36
Date Updated (+03): 10/01/2018, 15:51:36
@hitbtc-com

**Comment by baij-patel** [comment]
They are lying.  We have been victims of a scam.  I have been unable to withdraw ETH and TRX.  They post one excuse after another on their site.  I have reported to two crime agencies now.

**Comment by aaahmadi** [comment]
baji u want how many trx ? what tha ffffff give me ur wallet im payed u baby

**Comment by hitbtc-com** [comment]
Dear @kuakk, can you let us know if the issue's still relevant and provide us with a ticket number if it is? Thanks in advance!
