### ISSUE TITLE
Problem with /history/order parameter

### ISSUE THREAD

**Issue by acuberof** [hitbtc-com/hitbtc-api#84]
When I try to obtain my Orders History if I use the parameter 'symbol' it is ignored. I can put what I want that the result will be the same.

If I try with the command /history/trades (Which is quite similar) the parameter'symbol' works fine.

**Comment by acuberof** [comment]
I realised another error in this command. It does not returns the price (API documentation says the price is returned...)

**Comment by aaahmadi** [comment]
Does it mean to review my coins?

whats mean my coins is in my deposit yes ?
I was worried

**Comment by aaahmadi** [comment]
i have 2282800 life
and 10000more bmc i need my coins im backed my authy
i was worried sup

**Comment by divergence082** [comment]
+1 
I also noticed symbol parameter is ignored
and I've just checked the response - price field is absent

**Comment by divergence082** [comment]
curl -X GET -u "publicKey:secretKey" "https://api.hitbtc.com/api/2/history/order?symbol=FUNETH&from=2018-01-30T17:05Z&till=2018-01-30T18:05Z"

[{"id":15143574515,"clientOrderId":"id","symbol":"BCHETH","side":"sell","status":"canceled","type":"limit","timeInForce":"GTC","quantity":"1.52","cumQuantity":"0.00","createdAt":"2018-01-29T01:48:32.559Z","updatedAt":"2018-01-30T17:12:01.158Z"}]

1. Incorrect symbol in response
2. Price is absent

**Comment by kononencheg** [comment]
+1

**Comment by hitbtc-com** [comment]
FIXED

**Comment by divergence082** [comment]
Woohoo! Thanks!
