### ISSUE TITLE
Hitbtc is really HITSCAM or is it fixing the issue?

### ISSUE THREAD

**Issue by Lionie** [hitbtc-com/hitbtc-api#86]
I can see that Hitbtc still allows people/traders/newbies deposit ETH to the exchange, and right after traders /you deposit to your Hitbtc's EHT wallet, they will move your ETH away to their own wallet. Some of them owe ETH equivalent to 4Milion USD. However, Hitbtc does not allow anyone withdraw ETH and claims that the congestion caused the delay and its server is overload. IF it was, why were Hitbtc able to move the ETH out? Hitbtc have blocked my withdrawals for almost 2 weeks, i emailed them many times, and just received very simple answer, "we are checking the  issue." How irresponsible Hitbtc is. My concern is Hitbtc really a scammer??? If it was, then please stop it and just tell the whole world that "I, HITBTC, WILL STOP OFFERING THE EXCHANGES SERVICES, YOUR MONEY DEPOSIT TO HITBTC WILL BE LOST ". I am one of very new traders and poor, all my savings used for betting on the luck of XRP, and i just made a little profit. I need your help to support my withdrawal ASAP.

**Comment by aaahmadi** [comment]
no hit btc is not a scam 👎

**Comment by aaahmadi** [comment]
and fixing the issue <3

**Comment by Gkathuria2** [comment]
My XEM withdrawal is pending from last 60 hours

Operational id is a58bd9db-2f8f-44f7-b585-dd94913b6712

kindly check these tickets #251471
#251092

Now XEM is offline on receiving address, please cancel withdrawal request and add fund back.

@HitBTC_Support_Team

**Comment by hitbtc-com** [comment]
Dear @Lionie, can you please state whether your issue was resolved? Thanks in advance!

**Comment by Lionie** [comment]
Hi Hitbtc support,

Yes, the issue is settled and thank you so much

Lynn
