### ISSUE TITLE
The moment you deposit in hitbit you will feel hell Ticket ID #185484

### ISSUE THREAD

**Issue by leechangmin1** [hitbtc-com/hitbtc-api#88]
The moment you deposit in hitbit you will feel hell Ticket ID #185484

Hitbit who can not deposit nor withdraw properly
You seem to have no basis.

I requested a withdrawal a few days ago.
Seven days later, I canceled the transfer, not the coin transfer.

Health System Report Why did not I withdraw money when I made a withdrawal request again this time?

And can not real-time health system upload?

Please work straight.

**Comment by aaahmadi** [comment]
HITBTC PROTECTED COINS TO WRONG TREADES
IS NOT A SCAM DUDE

**Comment by hitbtc-com** [comment]
Dear @leechangmin1, your issue was resolved and your deposit was credited. We appreciate your choice to trade with HitBTC!
