### ISSUE TITLE
Tokens not showing up in deposit after 3 weeks 

### ISSUE THREAD

**Issue by elvis20ca** [hitbtc-com/hitbtc-api#90]
My tokens are not showing up in deposit after 3 weeks.  
Ticket ID #106056. I have over 20,000 USD of tokens that I cannot trade.  Can someone please resolve this ?

**Comment by aaahmadi** [comment]
im lost my 2fa cods and cant goin in my accounte too

**Comment by hitbtc-com** [comment]
Dear @elvis20ca, I believe your issue was already resolved.
Feel free to contact us anytime if you have any additional questions. Enjoy trading with HitBTC!
