### ISSUE TITLE
Send Bitcoin on USDT address ( Ref Ticket # 192649/169101 & 188683)

### ISSUE THREAD

**Issue by anupsingh1210** [hitbtc-com/hitbtc-api#97]
@hitbtc-com 
![btc wrong transfer 4](https://user-images.githubusercontent.com/35521020/35033397-f624b6fc-fb83-11e7-8170-58806640f7dd.jpg)
![btc wrong transfer 5](https://user-images.githubusercontent.com/35521020/35033398-f65f7f3a-fb83-11e7-8df0-9dbce15e95d8.jpg)
![btc wrong transfer](https://user-images.githubusercontent.com/35521020/35033399-f68a74ba-fb83-11e7-8733-cafcc2248626.jpg)

 would like to inform you that I already submitted the request and the Ref Ticket # 16101/188683/192649, Please note that i had send bitcoin from my Bitoasis wallet to my Hitbtc a/c, but by mistake i sent bitcoin on USDT address instead of BTC address, already send hundreds of mail with all the details. Hence would like to request you kindly rectify the same at the earliest possible.

https://blockchain.info/tx/ec08e62a4e6daff112046b8d9ea28e01e73819f90c21eb5df1979fc470829cf2

**Comment by hitbtc-com** [comment]
Dear @anupsingh1210, I believe your issue was already resolved.
Enjoy trading with HitBTC!
