### ISSUE TITLE
RequestTimeout: hitbtc GET http://api.hitbtc.com/api/1/public/BTCUSD/ticker request timeout

### ISSUE THREAD

**Issue by Jackzhangpan** [hitbtc-com/hitbtc-api#98]
how to solve?

**Comment by hitbtc-com** [comment]
it work:
time curl http://api.hitbtc.com/api/1/public/BTCUSD/ticker
{"ask":"10967.71","bid":"10963.05","last":"10959.80","low":"10846.30","high":"11465.52","open":"11223.94","volume":"5553.75","volume_quote":"61887038.9853","timestamp":1517317346773}
real	0m0.128s
user	0m0.012s
sys	0m0.000s
